// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BootstrapInfo carries live bootstrap progress from the provider's
 * ACTUAL state (Tor log lines / Psiphon tunnel events) — never from
 * timers.
 */
export class BootstrapInfo {
    /**
     * Creates a new BootstrapInfo instance.
     * @param {Partial<BootstrapInfo>} [$$source = {}] - The source object to create the BootstrapInfo.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["active"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 0-100 when active
             * @member
             * @type {number | undefined}
             */
            this["progress"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * last bootstrap tag/summary
             * @member
             * @type {string | undefined}
             */
            this["tag"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["complete"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["updated_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BootstrapInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BootstrapInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BootstrapInfo(/** @type {Partial<BootstrapInfo>} */($$parsedSource));
    }
}

/**
 * Endpoint is a local proxy endpoint discovered from the REAL
 * runtime (a port the provider actually listens on).
 */
export class Endpoint {
    /**
     * Creates a new Endpoint instance.
     * @param {Partial<Endpoint>} [$$source = {}] - The source object to create the Endpoint.
     */
    constructor($$source = {}) {
        if (!("network" in $$source)) {
            /**
             * Network is "socks5" or "http".
             * @member
             * @type {string}
             */
            this["network"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * Host is normally 127.0.0.1.
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * Port is the observed local port.
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Verified marks an endpoint whose listener was actually probed.
             * @member
             * @type {boolean | undefined}
             */
            this["verified"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Endpoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Endpoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Endpoint(/** @type {Partial<Endpoint>} */($$parsedSource));
    }
}

/**
 * Health is a measured health snapshot.
 */
export class Health {
    /**
     * Creates a new Health instance.
     * @param {Partial<Health>} [$$source = {}] - The source object to create the Health.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("process_alive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["process_alive"] = false;
        }
        if (!("listener_ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["listener_ready"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * LatencyMS is a MEASURED probe round trip through the local
             * endpoint (v0.9.8.1 semantics: 0 + Measured = sub-ms).
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["measured"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Health instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Health}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Health(/** @type {Partial<Health>} */($$parsedSource));
    }
}

/**
 * Info is the credential-free provider surface for the UI (§13).
 */
export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {Kind}
             */
            this["kind"] = Kind.$zero;
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {LifecycleState}
             */
            this["state"] = LifecycleState.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * process state when running
             * @member
             * @type {string | undefined}
             */
            this["runtime_state"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * download source or "user-provided"
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * short license name
             * @member
             * @type {string | undefined}
             */
            this["license"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * attribution notice
             * @member
             * @type {string | undefined}
             */
            this["notice"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_check"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * discovered from the real runtime
             * @member
             * @type {Endpoint[] | undefined}
             */
            this["endpoints"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * honest, runtime-derived
             * @member
             * @type {string[] | undefined}
             */
            this["capabilities"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["failure_reason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {BootstrapInfo | undefined}
             */
            this["bootstrap"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        const $$createField11_0 = $$createType2;
        const $$createField13_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("endpoints" in $$parsedSource) {
            $$parsedSource["endpoints"] = $$createField10_0($$parsedSource["endpoints"]);
        }
        if ("capabilities" in $$parsedSource) {
            $$parsedSource["capabilities"] = $$createField11_0($$parsedSource["capabilities"]);
        }
        if ("bootstrap" in $$parsedSource) {
            $$parsedSource["bootstrap"] = $$createField13_0($$parsedSource["bootstrap"]);
        }
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}

/**
 * Kind classifies providers.
 * @readonly
 * @enum {string}
 */
export const Kind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * KindCore: protocol-core backends (xray, v2ray, sing-box) driven
     * per node-configuration.
     */
    KindCore: "core",

    /**
     * KindTor: the Tor network engine (expert bundle, local SOCKS).
     */
    KindTor: "tor",

    /**
     * KindPsiphon: the Psiphon tunnel-core engine.
     */
    KindPsiphon: "psiphon",
};

/**
 * LifecycleState is the provider lifecycle state (§8/§9):
 * resolve → install → validate → start → bootstrap/ready → health →
 * stop → cleanup.
 * @readonly
 * @enum {string}
 */
export const LifecycleState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * StateNotInstalled: no verified binary in the workspace.
     */
    StateNotInstalled: "not_installed",

    /**
     * StateInstalling: the managed download pipeline is running.
     */
    StateInstalling: "installing",

    /**
     * StateInstalled: binary staged and validated, not running.
     */
    StateInstalled: "installed",

    /**
     * StateStarting: process launched, not yet ready.
     */
    StateStarting: "starting",

    /**
     * StateReady: process running and its local proxy endpoint(s)
     * accept connections (Tor: bootstrapped 100%; Psiphon: tunnels
     * up). Readiness is observed, never assumed.
     */
    StateReady: "ready",

    /**
     * StateStopping: shutdown in progress.
     */
    StateStopping: "stopping",

    /**
     * StateFailed: last lifecycle operation failed (reason recorded).
     */
    StateFailed: "failed",

    /**
     * StateDisabled: explicitly disabled by the user.
     */
    StateDisabled: "disabled",
};

// Private type creation functions
const $$createType0 = Endpoint.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = BootstrapInfo.createFrom;
