// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Config is the normalized representation of a VPN/proxy configuration.
 * 
 * Parsers convert external formats into Config objects.
 * Protocol engines later convert Config objects into core-specific
 * configurations.
 */
export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {Type}
             */
            this["type"] = Type.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Authentication / identity.
             * @member
             * @type {string | undefined}
             */
            this["uuid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Transport.
             * @member
             * @type {string | undefined}
             */
            this["network"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["service"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Security.
             * @member
             * @type {string | undefined}
             */
            this["security"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["server_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fingerprint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["public_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["short_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * WireGuard.
             * @member
             * @type {string | undefined}
             */
            this["private_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allowed_ips"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["mtu"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["persistent_keepalive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Source information.
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (!("working" in $$source)) {
            /**
             * Runtime information.
             * @member
             * @type {boolean}
             */
            this["working"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["tested_at"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField19_0 = $$createType0;
        const $$createField20_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("allowed_ips" in $$parsedSource) {
            $$parsedSource["allowed_ips"] = $$createField19_0($$parsedSource["allowed_ips"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField20_0($$parsedSource["dns"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * Type identifies the protocol used by a configuration.
 * @readonly
 * @enum {string}
 */
export const Type = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TypeVLESS: "vless",
    TypeVMess: "vmess",
    TypeTrojan: "trojan",
    TypeShadowsocks: "shadowsocks",
    TypeHysteria: "hysteria",
    TypeHysteria2: "hysteria2",
    TypeTUIC: "tuic",
    TypeWireGuard: "wireguard",
    TypeSOCKS: "socks",
    TypeHTTP: "http",
    TypeUnknown: "unknown",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
