// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Config {
    /**
     * Creates a new Config instance.
     * @param {Partial<Config>} [$$source = {}] - The source object to create the Config.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {Type}
             */
            this["type"] = Type.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Authentication / identity.
             * @member
             * @type {string | undefined}
             */
            this["uuid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Transport.
             * @member
             * @type {string | undefined}
             */
            this["network"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["service"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Security.
             * @member
             * @type {string | undefined}
             */
            this["security"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["server_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fingerprint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["public_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["short_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Insecure is the user-supplied "skip TLS verification" request
             * (v0.10.2: captured for the QUIC family — hysteria/hysteria2/
             * tuic — whose URI spec carries insecure=1; v0.10.1 silently
             * dropped it, making most real-world Hysteria2 configs
             * unusable). Deliberately NOT part of the fingerprint: it
             * changes TLS behavior, not the configuration identity.
             * @member
             * @type {boolean | undefined}
             */
            this["insecure"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Protocol details consumed by core backends. Parsers capture them
             * and backend adapters read them, but they are deliberately NOT part
             * of the fingerprint: identity is endpoint + credentials + transport,
             * so existing stored records keep stable keys across the v0.4
             * protocol-core upgrade (fingerprint stability is a
             * storage-compatibility guarantee, see docs/storage-format.md).
             * VLESS flow (xtls-rprx-vision).
             * @member
             * @type {string | undefined}
             */
            this["flow"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VLESS encryption (default none).
             * @member
             * @type {string | undefined}
             */
            this["encryption"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VMess legacy alterId.
             * @member
             * @type {number | undefined}
             */
            this["alter_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * VMess TCP header obfuscation.
             * @member
             * @type {string | undefined}
             */
            this["header_type"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TLS ALPN list.
             * @member
             * @type {string[] | undefined}
             */
            this["alpn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * REALITY spider path.
             * @member
             * @type {string | undefined}
             */
            this["spider_x"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.10.3 protocol-detail fields. v0.10.2 overloaded unrelated
             * slots (TUIC congestion_control → Network; Hysteria obfs →
             * Security; obfs-password → Host), which corrupted BOTH meanings:
             * the capability matcher treated "bbr" as a transport, and the
             * WS host header slot carried an obfuscation password. Each
             * value now lives in its semantic field and generates the
             * correct sing-box JSON. Not part of the fingerprint (tuning,
             * not identity).
             * v0.10.4 semantics note: Obfs means different things for the
             * two Hysteria protocols, matching each actual wire format:
             *   - Hysteria2: the obfs TYPE ("" | salamander | gecko) and
             *     ObfsPassword carries the obfuscation password — generated
             *     as the sing-box object {"type", "password"}.
             *   - Hysteria (v1): the obfuscation PASSWORD string itself
             *     (the v1 format has no type concept) — generated as the
             *     sing-box JSON string `"obfs": "..."`, omitted when empty.
             * TUIC: bbr | cubic | new_reno.
             * @member
             * @type {string | undefined}
             */
            this["congestion_control"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TUIC: native | quic.
             * @member
             * @type {string | undefined}
             */
            this["udp_relay_mode"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Hysteria2: salamander | gecko; Hysteria v1: obfs password string.
             * @member
             * @type {string | undefined}
             */
            this["obfs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Hysteria2 obfs password (object shape).
             * @member
             * @type {string | undefined}
             */
            this["obfs_password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.11.0 Encrypted Client Hello (TLS-layer detail, sing-box
             * tls.ech — verified against the pinned v1.14.0 binary).
             * 
             * Semantic model — one dedicated field per sing-box knob,
             * overloading nothing (Host/Network/Security/Fingerprint/
             * SpiderX stay untouched):
             *   ECHEnabled         → ech.enabled
             *   ECHConfig          → ech.config        (PEM "ECH CONFIGS")
             *   ECHConfigPath      → ech.config_path   (file containing the PEM)
             *   ECHQueryServerName → ech.query_server_name (DNS HTTPS query)
             * 
             * ECHConfig carries the canonical PEM form after Normalize:
             * a raw base64 ECHConfigList (the DNS HTTPS record `ech=`
             * payload shape) is wrapped into the PEM envelope during
             * normalization, because the pinned sing-box v1.14.0 accepts
             * ONLY the PEM form ("invalid ECH configs pem" otherwise —
             * verified empirically, see docs/protocols.md). Not part of
             * the fingerprint: ECH changes the TLS layer's negotiation,
             * not the configuration identity (same rationale as ALPN and
             * Insecure).
             * 
             * EVIDENCE SCOPE (do not upgrade): support is schema-level —
             * `sing-box check` + startup acceptance. No live ECH
             * negotiation with a real ECH server is claimed anywhere.
             * @member
             * @type {boolean | undefined}
             */
            this["ech_enabled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ech_config"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ech_config_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ech_query_server_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * WireGuard.
             * 
             * v0.10.3 semantics split: InterfaceAddress is the LOCAL
             * interface address list (the WireGuard INI "Address" — what the
             * tun interface gets); AllowedIPs is the PEER routing list (what
             * traffic the peer accepts). They are distinct concepts and must
             * never overload each other: v0.10.2 dropped the interface
             * address entirely and generated a WireGuard endpoint with no
             * local address at all.
             * @member
             * @type {string | undefined}
             */
            this["private_key"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["interface_address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["allowed_ips"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dns"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["mtu"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["persistent_keepalive"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Bandwidth caps for the QUIC family (v0.10.2). Hysteria (v1)
             * REQUIRES both — the pinned sing-box v1.14.0 refuses the
             * outbound without them ("missing upload speed") — while
             * Hysteria2 treats them as optional. Not part of the
             * fingerprint (link tuning, not identity).
             * @member
             * @type {number | undefined}
             */
            this["up_mbps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["down_mbps"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Source information.
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SourceTrust is the ROUTE-trust classification of the source this
             * configuration was ingested from (v0.9.8.6):
             * "official" | "user" | "public". Empty (legacy records) resolves
             * as "public" — untrusted by default. Reliability and reachability
             * measurements never promote a public route to trusted.
             * @member
             * @type {string | undefined}
             */
            this["source_trust"] = undefined;
        }
        if (!("working" in $$source)) {
            /**
             * Runtime information.
             * @member
             * @type {boolean}
             */
            this["working"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["tested_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.9.0 test metadata (§4): the backend that executed the last
             * test, the endpoint it targeted and the total test duration.
             * Runtime-only, never part of the fingerprint.
             * @member
             * @type {string | undefined}
             */
            this["test_backend"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["test_endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["test_duration_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.9.3 bounded observation history: the last TestHistoryLimit
             * test outcomes for this configuration (newest last). It is the
             * actual data the ranking engine scores — success rate, latency
             * stability and timeout frequency come from here, never invented.
             * Runtime-only: never part of the fingerprint, never uploaded.
             * @member
             * @type {TestObservation[] | undefined}
             */
            this["test_history"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Ping holds the latest repeated-sample TCP latency measurement
             * (min/median/avg/max/jitter/loss). Nil = never ping-tested.
             * Runtime-only: never part of the fingerprint.
             * @member
             * @type {PingMetrics | null | undefined}
             */
            this["ping"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * URLTest holds the latest HTTP connectivity measurement through
             * the candidate tunnel with its full phase breakdown (DNS/TCP/
             * TLS/TTFB/total). Nil = never URL-tested. Runtime-only: never
             * part of the fingerprint.
             * @member
             * @type {URLTestMetrics | null | undefined}
             */
            this["url_test"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Handshake holds the latest protocol-core handshake timing.
             * Runtime-only: never part of the fingerprint.
             * @member
             * @type {HandshakeMetrics | null | undefined}
             */
            this["handshake"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastSuccessAt is the last time this candidate provided verified
             * usable connectivity (Unix milliseconds) — the freshness anchor
             * for "Recently Verified" ranking. Runtime-only.
             * @member
             * @type {number | undefined}
             */
            this["last_success_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * FailureStreak counts consecutive failed verifications since the
             * last success; reset on every success. Runtime-only.
             * @member
             * @type {number | undefined}
             */
            this["failure_streak"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastFailureReason is the classified cause of the most recent
             * failure (timeout/refused/reset/handshake/verify), stored
             * without credentials. Runtime-only.
             * @member
             * @type {string | undefined}
             */
            this["last_failure_reason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastFailureAt is the time of the most recent FAILED
             * verification (Unix milliseconds; 0 = no recorded failure).
             * Together with LastSuccessAt it gives the ranking layer an
             * honest verification age on both sides (fresh success vs
             * fresh failure). Runtime-only.
             * @member
             * @type {number | undefined}
             */
            this["last_failure_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastFailureClass is the FAILURE CLASS of the most recent
             * failure — one of the FailureClass* constants (dns, tcp,
             * tls, handshake, listener, verify, reset, timeout,
             * transport). Unlike LastFailureReason (free text), the class
             * is a stable vocabulary the ranking layer and recovery
             * pipeline can reason over ("after two handshake-class
             * failures prefer a different transport"). Runtime-only.
             * @member
             * @type {string | undefined}
             */
            this["last_failure_class"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Config instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Config}
     */
    static createFrom($$source = {}) {
        const $$createField23_0 = $$createType0;
        const $$createField34_0 = $$createType0;
        const $$createField35_0 = $$createType0;
        const $$createField36_0 = $$createType0;
        const $$createField49_0 = $$createType2;
        const $$createField50_0 = $$createType4;
        const $$createField51_0 = $$createType6;
        const $$createField52_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("alpn" in $$parsedSource) {
            $$parsedSource["alpn"] = $$createField23_0($$parsedSource["alpn"]);
        }
        if ("interface_address" in $$parsedSource) {
            $$parsedSource["interface_address"] = $$createField34_0($$parsedSource["interface_address"]);
        }
        if ("allowed_ips" in $$parsedSource) {
            $$parsedSource["allowed_ips"] = $$createField35_0($$parsedSource["allowed_ips"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField36_0($$parsedSource["dns"]);
        }
        if ("test_history" in $$parsedSource) {
            $$parsedSource["test_history"] = $$createField49_0($$parsedSource["test_history"]);
        }
        if ("ping" in $$parsedSource) {
            $$parsedSource["ping"] = $$createField50_0($$parsedSource["ping"]);
        }
        if ("url_test" in $$parsedSource) {
            $$parsedSource["url_test"] = $$createField51_0($$parsedSource["url_test"]);
        }
        if ("handshake" in $$parsedSource) {
            $$parsedSource["handshake"] = $$createField52_0($$parsedSource["handshake"]);
        }
        return new Config(/** @type {Partial<Config>} */($$parsedSource));
    }
}

/**
 * HandshakeMetrics records the protocol-core handshake phase of a
 * test (core start → inbound ready), the v0.9.3 DurationMS split
 * into its meaningful part.
 */
export class HandshakeMetrics {
    /**
     * Creates a new HandshakeMetrics instance.
     * @param {Partial<HandshakeMetrics>} [$$source = {}] - The source object to create the HandshakeMetrics.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * ReadyMS is the time from core process start to the inbound
             * listener accepting connections.
             * @member
             * @type {number | undefined}
             */
            this["ready_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ProbeMS is the end-to-end probe time through the ready tunnel
             * (when the probe ran).
             * @member
             * @type {number | undefined}
             */
            this["probe_ms"] = undefined;
        }
        if (!("ok" in $$source)) {
            /**
             * OK reports whether the handshake completed.
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("at" in $$source)) {
            /**
             * At is the measurement time (Unix milliseconds).
             * @member
             * @type {number}
             */
            this["at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HandshakeMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HandshakeMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HandshakeMetrics(/** @type {Partial<HandshakeMetrics>} */($$parsedSource));
    }
}

/**
 * PingMetrics is the outcome of a repeated-sample latency measurement
 * against a candidate's endpoint (TCP handshake RTT — see
 * engine/tester/ping.go for why FreeIran measures TCP, not ICMP).
 * 
 * Every field is derived from the recorded samples; there is no
 * interpolation and no invented value. Zero PingMetrics (Samples=0)
 * means "not measured". A nonzero Samples with MinMS/MedianMS == 0
 * means "measured, sub-millisecond" (v0.9.8.1): millisecond fields
 * are projections, and SubMS flags the sub-millisecond case
 * explicitly for display ("< 1 ms").
 */
export class PingMetrics {
    /**
     * Creates a new PingMetrics instance.
     * @param {Partial<PingMetrics>} [$$source = {}] - The source object to create the PingMetrics.
     */
    constructor($$source = {}) {
        if (!("min_ms" in $$source)) {
            /**
             * Min/Max are the fastest and slowest successful samples.
             * @member
             * @type {number}
             */
            this["min_ms"] = 0;
        }
        if (!("max_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * SubMS reports that the median sample was faster than one
             * millisecond (the projected fields read 0). It is the explicit
             * measured-sub-millisecond marker (rule R4, engine/tester/latency.go).
             * @member
             * @type {boolean | undefined}
             */
            this["sub_ms"] = undefined;
        }
        if (!("median_ms" in $$source)) {
            /**
             * Median is the 50th percentile of the successful samples
             * (resistant to outliers, the number the "Lowest Median Ping"
             * sort uses).
             * @member
             * @type {number}
             */
            this["median_ms"] = 0;
        }
        if (!("avg_ms" in $$source)) {
            /**
             * Avg is the arithmetic mean of the successful samples.
             * @member
             * @type {number}
             */
            this["avg_ms"] = 0;
        }
        if (!("jitter_ms" in $$source)) {
            /**
             * Jitter is the mean absolute deviation between consecutive
             * successful samples (instability of the path, in ms).
             * @member
             * @type {number}
             */
            this["jitter_ms"] = 0;
        }
        if (!("packet_loss" in $$source)) {
            /**
             * PacketLoss is the fraction of samples that failed (timeouts +
             * refused + reset) in [0,1].
             * @member
             * @type {number}
             */
            this["packet_loss"] = 0;
        }
        if (!("samples" in $$source)) {
            /**
             * Samples counts the successful round trips; Failures counts
             * every failed attempt; Timeouts counts the subset of failures
             * that were deadline exceeded (path black-holing).
             * @member
             * @type {number}
             */
            this["samples"] = 0;
        }
        if (!("failures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failures"] = 0;
        }
        if (!("timeouts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeouts"] = 0;
        }
        if (!("at" in $$source)) {
            /**
             * At is the measurement time (Unix milliseconds). Staleness is
             * judged against this timestamp, never against discovery time.
             * @member
             * @type {number}
             */
            this["at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PingMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PingMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PingMetrics(/** @type {Partial<PingMetrics>} */($$parsedSource));
    }
}

/**
 * TestObservation is one recorded test outcome.
 */
export class TestObservation {
    /**
     * Creates a new TestObservation instance.
     * @param {Partial<TestObservation>} [$$source = {}] - The source object to create the TestObservation.
     */
    constructor($$source = {}) {
        if (!("at" in $$source)) {
            /**
             * At is the observation time (Unix milliseconds).
             * @member
             * @type {number}
             */
            this["at"] = 0;
        }
        if (!("working" in $$source)) {
            /**
             * Working reports whether the configuration served traffic.
             * @member
             * @type {boolean}
             */
            this["working"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * LatencyMS is the measured round-trip time (0 when failed).
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TimedOut marks failures that were timeouts — the ranking
             * layer penalises them harder than refusals.
             * @member
             * @type {boolean | undefined}
             */
            this["timed_out"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Backend is the core that executed the test (informational).
             * @member
             * @type {string | undefined}
             */
            this["backend"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * FailureClass is the v0.11.0 classification of a failed
             * observation (one of the FailureClass* constants; "" for
             * successes and unclassifiable failures). It is derived from
             * the same observed error text as LastFailureReason — never
             * invented — so per-class evidence accumulates in the bounded
             * history ring the ranking layer already scores from.
             * @member
             * @type {string | undefined}
             */
            this["failure_class"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestObservation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestObservation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestObservation(/** @type {Partial<TestObservation>} */($$parsedSource));
    }
}

/**
 * Type identifies the protocol used by a configuration.
 * @readonly
 * @enum {string}
 */
export const Type = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TypeVLESS: "vless",
    TypeVMess: "vmess",
    TypeTrojan: "trojan",
    TypeShadowsocks: "shadowsocks",
    TypeHysteria: "hysteria",
    TypeHysteria2: "hysteria2",
    TypeTUIC: "tuic",
    TypeWireGuard: "wireguard",
    TypeSOCKS: "socks",
    TypeHTTP: "http",
    TypeUnknown: "unknown",
};

/**
 * URLTestMetrics is the outcome of one HTTP connectivity measurement
 * THROUGH the candidate tunnel — proving usable connectivity, not
 * merely that a host responds.
 * 
 * Phase timings are the real httptrace phase durations in
 * milliseconds; -1 marks a phase that did not complete (e.g. TLS
 * timing on a plaintext request) and 0 is a valid, very fast phase.
 */
export class URLTestMetrics {
    /**
     * Creates a new URLTestMetrics instance.
     * @param {Partial<URLTestMetrics>} [$$source = {}] - The source object to create the URLTestMetrics.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * URL is the test target that was requested (recorded so results
             * are comparable across configuration changes).
             * @member
             * @type {string | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DNSMS is the name-resolution phase (0 when the target was an
             * IP literal or the proxy resolved it remotely).
             * @member
             * @type {number | undefined}
             */
            this["dns_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ConnectMS is the TCP connection phase.
             * @member
             * @type {number | undefined}
             */
            this["connect_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TLSMS is the TLS handshake phase (-1 when no TLS was used).
             * @member
             * @type {number | undefined}
             */
            this["tls_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TTFBMS is time-to-first-byte from the request write to the
             * first response byte.
             * @member
             * @type {number | undefined}
             */
            this["ttfb_ms"] = undefined;
        }
        if (!("total_ms" in $$source)) {
            /**
             * TotalMS is the complete request wall time.
             * @member
             * @type {number}
             */
            this["total_ms"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * Status is the HTTP status code (0 when the request never
             * completed).
             * @member
             * @type {number}
             */
            this["status"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * Bytes is the response body size actually received.
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (!("ok" in $$source)) {
            /**
             * OK reports usable connectivity: the request completed with a
             * 2xx/3xx status within the configured timeout.
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Timeout marks a failure caused by the configured deadline
             * (versus refused/reset/protocol errors).
             * @member
             * @type {boolean | undefined}
             */
            this["timeout"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Error is the failure classification (empty on success); it is
             * derived from the transport error, never raw credentials.
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * At is the measurement time (Unix milliseconds).
             * @member
             * @type {number}
             */
            this["at"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new URLTestMetrics instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {URLTestMetrics}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new URLTestMetrics(/** @type {Partial<URLTestMetrics>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = TestObservation.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = PingMetrics.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = URLTestMetrics.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = HandshakeMetrics.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
