package coremgr

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"

	firerrors "github.com/Parsaetak/FreeIran/engine/errors"
)

// queryVersion asks a core binary for its version string. Returns
// the first non-empty line of stdout (trimmed).
func (m *Manager) queryVersion(ctx context.Context, path string, args []string) (string, error) {
	if len(args) == 0 {
		args = []string{"version"}
	}

	probeCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	var stdout, stderr bytes.Buffer
	cmd := exec.CommandContext(probeCtx, path, args...)
	applyHiddenConsole(cmd) // never flash a console window (§v0.9.0)
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("version query failed: %w (stderr=%s)", err, stderr.String())
	}

	line := strings.SplitN(strings.TrimSpace(stdout.String()), "\n", 2)[0]
	return strings.TrimSpace(line), nil
}

// validateExecutable runs the backend's "test" / "check" subcommand
// against a minimal valid config to confirm the binary accepts the
// format the manager expects. The minimal config is generated by the
// backend adapter, but here we use a generic minimal SOCKS inbound
// document that all three cores accept.
func (m *Manager) validateExecutable(ctx context.Context, name CoreName, path string, src Source) error {
	// Generate a minimal config in the backend's native format.
	cfgBytes, err := minimalConfig(name)
	if err != nil {
		return fmt.Errorf("generate minimal config: %w", err)
	}

	tmpDir, err := os.MkdirTemp(m.tempRoot(), "coremgr-validate-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmpDir)

	cfgPath := filepath.Join(tmpDir, "config.json")
	if err := os.WriteFile(cfgPath, cfgBytes, 0o600); err != nil {
		return err
	}

	checkCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	args := append(append([]string{}, src.ConfigCheckArgs...), cfgPath)
	var stderr bytes.Buffer
	cmd := exec.CommandContext(checkCtx, path, args...)
	applyHiddenConsole(cmd) // never flash a console window (§v0.9.0)
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("config validation failed: %w (stderr=%s)", err, stderr.String())
	}

	return nil
}

// smokeTest launches the binary with a minimal SOCKS inbound on a
// random port, waits for the listener to accept, then shuts it down.
// It is the manager's own readiness check, separate from the protocol-
// core execution boundary used by the connection manager (which uses
// real outbound configurations).
func (m *Manager) smokeTest(ctx context.Context, name CoreName, path string, src Source) HealthResult {
	result := HealthResult{
		CheckedAt: time.Now().UTC(),
	}

	if _, err := os.Stat(path); err != nil {
		result.Details = fmt.Sprintf("executable missing: %v", err)
		return result
	}
	result.ExecutableExists = true

	version, err := m.queryVersion(ctx, path, src.VersionProbeArgs)
	if err != nil || version == "" {
		result.Details = fmt.Sprintf("version query failed: %v", err)
		return result
	}
	result.VersionQuery = true

	// Validate the executable accepts a minimal config.
	if err := m.validateExecutable(ctx, name, path, src); err != nil {
		result.Details = fmt.Sprintf("config validation failed: %v", err)
		return result
	}
	result.ConfigValidate = true

	// Launch + listener readiness + clean shutdown.
	port, err := reservePort()
	if err != nil {
		result.Details = fmt.Sprintf("reserve port: %v", err)
		return result
	}

	cfgBytes, err := smokeRunConfig(name, port)
	if err != nil {
		result.Details = fmt.Sprintf("smoke config: %v", err)
		return result
	}

	tmpDir, err := os.MkdirTemp(m.tempRoot(), "coremgr-smoke-*")
	if err != nil {
		result.Details = fmt.Sprintf("tempdir: %v", err)
		return result
	}
	defer os.RemoveAll(tmpDir)

	cfgPath := filepath.Join(tmpDir, "config.json")
	if err := os.WriteFile(cfgPath, cfgBytes, 0o600); err != nil {
		result.Details = fmt.Sprintf("write smoke config: %v", err)
		return result
	}

	runCtx, cancel := context.WithTimeout(ctx, 8*time.Second)
	defer cancel()

	args := append(append([]string{}, src.RunArgs...), cfgPath)
	var stderr bytes.Buffer
	cmd := exec.CommandContext(runCtx, path, args...)
	applyHiddenConsole(cmd) // never flash a console window (§v0.9.0)
	cmd.Stderr = &stderr

	if err := cmd.Start(); err != nil {
		result.Details = fmt.Sprintf("smoke start: %v", err)
		return result
	}

	endpoint := fmt.Sprintf("127.0.0.1:%d", port)
	ready := waitForEndpoint(runCtx, endpoint, 5*time.Second)
	if !ready {
		_ = cmd.Process.Kill()
		_ = cmd.Wait()
		result.Details = "smoke listener not ready within 5s"
		return result
	}
	result.SmokeLaunch = true

	// Polite shutdown with Windows-safe semantics: a detached,
	// console-less child cannot receive console control events, so
	// gracefulStop falls back to TerminateProcess there. The guarantee
	// under test is deterministic termination — no orphan core.
	done := make(chan error, 1)
	go func() { done <- cmd.Wait() }()

	clean, detail := gracefulStop(cmd, done, 3*time.Second)
	result.CleanShutdown = clean

	if !clean {
		result.Details = "smoke shutdown timed out (killed)"
	} else if stderr.Len() > 0 {
		result.Details = detail
	}

	result.OK = result.ExecutableExists && result.VersionQuery && result.ConfigValidate && result.SmokeLaunch && result.CleanShutdown
	return result
}

// HealthCheck re-runs the smoke test against the active binary and
// updates the manifest. It does NOT install or update.
func (m *Manager) HealthCheck(ctx context.Context, name CoreName) (HealthResult, error) {
	unlock := m.lock(name)
	defer unlock()

	src, ok := m.sources[name]
	if !ok {
		return HealthResult{}, fmt.Errorf("no source for core %s", name)
	}

	// Snapshot the manifest under RLock so we can check State and
	// BinaryPath without holding the lock during the smoke test.
	snap, _ := m.snapshotManifest(name)
	binaryPath := snap.BinaryPath
	if binaryPath == "" {
		binaryPath = m.BinaryPath(name)
		// Persist the resolved path so future calls skip the lookup.
		_ = m.updateManifest(name, func(mf *Manifest) {
			if mf.BinaryPath == "" {
				mf.BinaryPath = binaryPath
			}
		})
	}
	if snap.State == StateInstalling {
		// Refuse to health-check while an install is in flight.
		return HealthResult{}, ErrAlreadyInstalling
	}
	_ = m.setState(name, StateChecking)

	result := m.smokeTest(ctx, name, binaryPath, src)

	_ = m.updateManifest(name, func(mf *Manifest) {
		mf.LastHealthCheck = time.Now().UTC()
		mf.LastHealthResult = result
		if result.OK {
			mf.State = StateReady
		} else {
			mf.State = StateBroken
		}
		mf.UpdatedAt = time.Now().UTC()
	})

	m.logger.Info(Subsystem, "health_check",
		"core %s health: ok=%v (exe=%v ver=%v cfg=%v launch=%v shutdown=%v)",
		name, result.OK, result.ExecutableExists, result.VersionQuery,
		result.ConfigValidate, result.SmokeLaunch, result.CleanShutdown)

	return result, nil
}

// HealthCheckAll runs a health check for every core in parallel.
func (m *Manager) HealthCheckAll(ctx context.Context) map[CoreName]HealthResult {
	results := make(map[CoreName]HealthResult, len(AllCores))
	var wg sync.WaitGroup

	for _, name := range AllCores {
		wg.Add(1)
		go func(n CoreName) {
			defer wg.Done()
			r, _ := m.HealthCheck(ctx, n)
			results[n] = r
		}(name)
	}

	wg.Wait()
	return results
}

// Rollback swaps the retained previous version back into the active
// path and re-runs the smoke test. If the rollback binary is missing
// or fails its smoke test, State becomes Broken.
func (m *Manager) Rollback(ctx context.Context, name CoreName) error {
	unlock := m.lock(name)
	defer unlock()

	mf, ok := m.Info(name)
	if !ok || mf.PreviousPath == "" {
		return ErrNoRollbackTarget
	}

	src := m.sources[name]

	if _, err := os.Stat(mf.PreviousPath); err != nil {
		return firerrors.New(firerrors.KindEnvironment,
			Subsystem, "rollback",
			"rollback binary missing: %s", mf.PreviousPath)
	}

	// Move the current binary aside (it becomes the new rollback
	// target — the user can roll forward again).
	currentPath := m.BinaryPath(name)
	backupPath := mf.PreviousPath + ".rollforward"
	_ = os.Remove(backupPath)
	if err := os.Rename(currentPath, backupPath); err != nil {
		return firerrors.Wrap(err, firerrors.KindEnvironment,
			Subsystem, "rollback",
			"move current binary aside: %s", currentPath)
	}

	// Activate the rollback binary.
	if err := os.Rename(mf.PreviousPath, currentPath); err != nil {
		// Restore the original.
		_ = os.Rename(backupPath, currentPath)
		return firerrors.Wrap(err, firerrors.KindEnvironment,
			Subsystem, "rollback",
			"activate rollback: %s", mf.PreviousPath)
	}

	// Query the rollback version.
	version, err := m.queryVersion(ctx, currentPath, src.VersionProbeArgs)
	if err != nil {
		version = "unknown"
	}

	// Smoke-test the rolled-back binary.
	result := m.smokeTest(ctx, name, currentPath, src)

	// Update manifest under m.mu via updateManifest (which also persists).
	_ = m.updateManifest(name, func(mf *Manifest) {
		mf.Version = version
		mf.BinaryPath = currentPath
		mf.State = StateReady
		mf.LastHealthCheck = time.Now().UTC()
		mf.LastHealthResult = result
		mf.PreviousPath = backupPath
		mf.PreviousVersion = ""
		mf.PreviousChecksum = ""
		mf.UpdatedAt = time.Now().UTC()
		if !result.OK {
			mf.State = StateBroken
		}
	})

	m.logger.Info(Subsystem, "rollback_complete",
		"core %s rolled back to %s (ok=%v)", name, version, result.OK)

	return nil
}

// reservePort allocates a random free port for the smoke test.
func reservePort() (int, error) {
	return reserveLocalPort("127.0.0.1")
}

// waitForEndpoint polls a TCP endpoint until it accepts or the
// timeout elapses.
func waitForEndpoint(ctx context.Context, endpoint string, timeout time.Duration) bool {
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		select {
		case <-ctx.Done():
			return false
		default:
		}
		if probeOnce(endpoint) {
			return true
		}
		time.Sleep(50 * time.Millisecond)
	}
	return false
}

// minimalConfig returns a backend-specific minimal config that the
// "test"/"check" subcommand should accept. It exercises the
// backend's config parser without launching a listener.
func minimalConfig(name CoreName) ([]byte, error) {
	switch name {
	case CoreXray, CoreV2Ray:
		// V4 format: a SOCKS inbound on 127.0.0.1 + a blackhole outbound.
		return []byte(`{
  "log": {"loglevel": "warning"},
  "inbounds": [
    {"port": "1080", "listen": "127.0.0.1", "protocol": "socks", "settings": {"auth": "noauth"}}
  ],
  "outbounds": [
    {"protocol": "freedom", "settings": {}},
    {"protocol": "blackhole", "settings": {}, "tag": "block"}
  ]
}`), nil
	case CoreSingBox:
		return []byte(`{
  "log": {"level": "warn"},
  "inbounds": [
    {"type": "socks", "tag": "socks-in", "listen": "127.0.0.1", "listen_port": 1080}
  ],
  "outbounds": [
    {"type": "direct", "tag": "direct"},
    {"type": "block", "tag": "block"}
  ]
}`), nil
	default:
		return nil, fmt.Errorf("unknown core: %s", name)
	}
}

// smokeRunConfig returns a backend-specific config that listens on
// the given port for the smoke launch test.
func smokeRunConfig(name CoreName, port int) ([]byte, error) {
	switch name {
	case CoreXray, CoreV2Ray:
		return []byte(fmt.Sprintf(`{
  "log": {"loglevel": "warning"},
  "inbounds": [
    {"port": "%d", "listen": "127.0.0.1", "protocol": "socks", "settings": {"auth": "noauth"}}
  ],
  "outbounds": [
    {"protocol": "freedom", "settings": {}}
  ]
}`, port)), nil
	case CoreSingBox:
		return []byte(fmt.Sprintf(`{
  "log": {"level": "warn"},
  "inbounds": [
    {"type": "socks", "tag": "socks-in", "listen": "127.0.0.1", "listen_port": %d}
  ],
  "outbounds": [
    {"type": "direct", "tag": "direct"}
  ]
}`, port)), nil
	default:
		return nil, fmt.Errorf("unknown core: %s", name)
	}
}

// probeOnce dials a TCP endpoint once.
func probeOnce(endpoint string) bool {
	conn, err := dialTCP(endpoint, 500*time.Millisecond)
	if err != nil {
		return false
	}
	_ = conn.Close()
	return true
}
