// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SourceResult reports the outcome for one source.
 */
export class SourceResult {
    /**
     * Creates a new SourceResult instance.
     * @param {Partial<SourceResult>} [$$source = {}] - The source object to create the SourceResult.
     */
    constructor($$source = {}) {
        if (!("source_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_id"] = "";
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("discovered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discovered"] = 0;
        }
        if (!("unique" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unique"] = 0;
        }
        if (!("unchanged" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unchanged"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content_hash"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceResult(/** @type {Partial<SourceResult>} */($$parsedSource));
    }
}

/**
 * Stats is the pipeline run summary.
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("sources_total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sources_total"] = 0;
        }
        if (!("sources_ok" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sources_ok"] = 0;
        }
        if (!("sources_failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sources_failed"] = 0;
        }
        if (!("sources_unchanged" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sources_unchanged"] = 0;
        }
        if (!("discovered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discovered"] = 0;
        }
        if (!("duplicates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicates"] = 0;
        }
        if (!("persisted" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["persisted"] = 0;
        }
        if (!("invalid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["invalid"] = 0;
        }
        if (!("per_source" in $$source)) {
            /**
             * @member
             * @type {SourceResult[]}
             */
            this["per_source"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("per_source" in $$parsedSource) {
            $$parsedSource["per_source"] = $$createField8_0($$parsedSource["per_source"]);
        }
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SourceResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
