// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Settings is the current set of tunable values. The booster writes
 * these; subsystems read them via Snapshot().
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("QueueConcurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["QueueConcurrency"] = 0;
        }
        if (!("IngestionConcurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["IngestionConcurrency"] = 0;
        }
        if (!("ParserConcurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ParserConcurrency"] = 0;
        }
        if (!("BatchSize" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["BatchSize"] = 0;
        }
        if (!("QueueDepth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["QueueDepth"] = 0;
        }
        if (!("CacheEntries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["CacheEntries"] = 0;
        }
        if (!("ChunkFlushBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ChunkFlushBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}
