// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CoreBinary describes one discovered protocol core.
 */
export class CoreBinary {
    /**
     * Creates a new CoreBinary instance.
     * @param {Partial<CoreBinary>} [$$source = {}] - The source object to create the CoreBinary.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Origin is where the executable was found (managed, path,
             * system, user) — v0.9.14 ownership/origin reporting.
             * @member
             * @type {string | undefined}
             */
            this["origin"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Ownership distinguishes FreeIran-managed binaries from external
             * ones (external binaries are only referenced, never modified).
             * @member
             * @type {string | undefined}
             */
            this["ownership"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CoreBinary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CoreBinary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CoreBinary(/** @type {Partial<CoreBinary>} */($$parsedSource));
    }
}

/**
 * Info describes the runtime environment.
 */
export class Info {
    /**
     * Creates a new Info instance.
     * @param {Partial<Info>} [$$source = {}] - The source object to create the Info.
     */
    constructor($$source = {}) {
        if (!("os" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["os"] = "";
        }
        if (!("arch" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["arch"] = "";
        }
        if (!("go_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["go_version"] = "";
        }
        if (!("num_cpu" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["num_cpu"] = 0;
        }
        if (!("hostname" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["hostname"] = "";
        }
        if (!("platform_note" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["platform_note"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Info instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Info}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Info(/** @type {Partial<Info>} */($$parsedSource));
    }
}

/**
 * WorkspaceStatus is the persisted migration record.
 */
export class WorkspaceStatus {
    /**
     * Creates a new WorkspaceStatus instance.
     * @param {Partial<WorkspaceStatus>} [$$source = {}] - The source object to create the WorkspaceStatus.
     */
    constructor($$source = {}) {
        if (!("version" in $$source)) {
            /**
             * Version is the status format version.
             * @member
             * @type {number}
             */
            this["version"] = 0;
        }
        if (!("migrated" in $$source)) {
            /**
             * Migrated reports whether a legacy location was copied in.
             * @member
             * @type {boolean}
             */
            this["migrated"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Source is the legacy root the data was copied from.
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * MigratedAt is the completion time (UTC, RFC 3339).
             * @member
             * @type {string | undefined}
             */
            this["migrated_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Files and Bytes describe the verified copy.
             * @member
             * @type {number | undefined}
             */
            this["files"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Skipped explains why no migration was attempted.
             * @member
             * @type {string | undefined}
             */
            this["skipped"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceStatus(/** @type {Partial<WorkspaceStatus>} */($$parsedSource));
    }
}
