// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Channel selects which release channel to consult for updates.
 * @readonly
 * @enum {string}
 */
export const Channel = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ChannelStable: "stable",
    ChannelPrerelease: "prerelease",
};

/**
 * CoreName is the canonical identifier of a managed protocol core.
 * @readonly
 * @enum {string}
 */
export const CoreName = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * CoreXray is the Xray-core backend (XTLS / REALITY / Vision / XHTTP).
     */
    CoreXray: "xray",

    /**
     * CoreV2Ray is the V2Fly V2Ray-core backend (classic V4 format).
     */
    CoreV2Ray: "v2ray",

    /**
     * CoreSingBox is the sing-box backend (native JSON dialect).
     */
    CoreSingBox: "sing-box",
};

/**
 * HealthResult records the outcome of a smoke-test against one core.
 */
export class HealthResult {
    /**
     * Creates a new HealthResult instance.
     * @param {Partial<HealthResult>} [$$source = {}] - The source object to create the HealthResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("executable_exists" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["executable_exists"] = false;
        }
        if (!("version_query" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["version_query"] = false;
        }
        if (!("config_validate" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["config_validate"] = false;
        }
        if (!("smoke_launch" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["smoke_launch"] = false;
        }
        if (!("clean_shutdown" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clean_shutdown"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HealthResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthResult(/** @type {Partial<HealthResult>} */($$parsedSource));
    }
}

/**
 * InstallState is the persisted lifecycle state of one managed core.
 * @readonly
 * @enum {string}
 */
export const InstallState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    StateNotInstalled: "not_installed",
    StateInstalling: "installing",
    StateInstalled: "installed",
    StateChecking: "checking",
    StateReady: "ready",
    StateBroken: "broken",
    StateUpdateAvailable: "update_available",
    StateDisabled: "disabled",
};

/**
 * Manifest is the persisted state of one managed core.
 */
export class Manifest {
    /**
     * Creates a new Manifest instance.
     * @param {Partial<Manifest>} [$$source = {}] - The source object to create the Manifest.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {CoreName}
             */
            this["name"] = CoreName.$zero;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {InstallState}
             */
            this["state"] = InstallState.$zero;
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("channel" in $$source)) {
            /**
             * @member
             * @type {Channel}
             */
            this["channel"] = Channel.$zero;
        }
        if (!("binary_path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["binary_path"] = "";
        }
        if (!("checksum_sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checksum_sha256"] = "";
        }
        if (!("source_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_url"] = "";
        }
        if (!("release_tag" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_tag"] = "";
        }
        if (!("release_date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_date"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("release_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_url"] = "";
        }
        if (!("installed_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installed_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last_checked" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_checked"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last_health_check" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_health_check"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last_health_result" in $$source)) {
            /**
             * @member
             * @type {HealthResult}
             */
            this["last_health_result"] = (new HealthResult());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["previous_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["previous_checksum"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["previous_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * FailureReason is the human-readable explanation for why the
             * core is in the Broken state (v0.9.0: every failed state must
             * carry a useful reason, not just a code).
             * @member
             * @type {string | undefined}
             */
            this["failure_reason"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * FailureStage is the pipeline step that failed (e.g. "download").
             * @member
             * @type {string | undefined}
             */
            this["failure_stage"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LatestKnown is the newest upstream version seen by the last
             * update check ("update available" without a re-query).
             * 
             * v0.9.13: the retained upstream snapshot is COMPLETED with the
             * release tag and the selected platform asset's download size, so
             * the UI can show the real update target and size across restarts
             * without re-querying the release API. All three fields are
             * optional (omitempty): manifests written by older versions load
             * unchanged, and a zero size honestly means "unavailable" — the
             * UI shows a fallback, never a guess. A channel change clears the
             * snapshot because it was selected under the previous channel.
             * @member
             * @type {string | undefined}
             */
            this["latest_known"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latest_tag"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latest_asset_size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ---- v0.9.14: ownership, provenance and reuse evidence ----------
             * 
             * All fields are optional: manifests written by v0.9.12/v0.9.13
             * load unchanged (unknown fields are never erased), and an empty
             * Ownership means the historical default — a FreeIran-managed
             * binary.
             * 
             * Ownership is "managed" (FreeIran-owned, installed/updated/
             * removed by the workspace) or "external" (an already-installed
             * binary FreeIran only REFERENCES — never deleted, renamed or
             * overwritten; Disable/Remove/Rollback clear the reference and
             * preserve the file).
             * @member
             * @type {string | undefined}
             */
            this["ownership"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Origin records where the active binary came from: "managed",
             * "path" (OS PATH lookup), "system" (known platform installation
             * location) or "user" (user-supplied adoption).
             * @member
             * @type {string | undefined}
             */
            this["origin"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ExternalPath is the canonical path of the referenced external
             * executable (equal to BinaryPath while the external reference is
             * active). When it disappears the runtime rediscoveres
             * alternatives instead of trusting a false "ready" state.
             * @member
             * @type {string | undefined}
             */
            this["external_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Trust distinguishes "upstream-verified" (SHA-256 matches the
             * authoritative upstream asset digest) from "locally-validated"
             * (probes and passes its smoke test, no authoritative digest
             * match available). A matching version string alone is NEVER
             * proof of provenance.
             * @member
             * @type {string | undefined}
             */
            this["trust"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * StatusNote carries an honest, non-failure status remark, e.g.
             * "newer than stable; automatic downgrade refused".
             * @member
             * @type {string | undefined}
             */
            this["status_note"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * BinarySize/BinaryModTime are the file identity the manifest was
             * written under; the reuse-first install path compares them to
             * prove the binary is unchanged before trusting recorded evidence.
             * @member
             * @type {number | undefined}
             */
            this["binary_size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["binary_mod_time"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastDecision is the v0.9.14 reuse decision of the last install
             * call (managed-current, system-current, system-newer,
             * system-older-but-working, managed-healthy, needs-update,
             * needs-download, invalid-local, not-found).
             * @member
             * @type {string | undefined}
             */
            this["last_decision"] = undefined;
        }
        if (!("updated_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updated_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manifest}
     */
    static createFrom($$source = {}) {
        const $$createField13_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("last_health_result" in $$parsedSource) {
            $$parsedSource["last_health_result"] = $$createField13_0($$parsedSource["last_health_result"]);
        }
        return new Manifest(/** @type {Partial<Manifest>} */($$parsedSource));
    }
}

/**
 * UpdateInfo is the result of checking for updates.
 */
export class UpdateInfo {
    /**
     * Creates a new UpdateInfo instance.
     * @param {Partial<UpdateInfo>} [$$source = {}] - The source object to create the UpdateInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {CoreName}
             */
            this["name"] = CoreName.$zero;
        }
        if (!("current_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["current_version"] = "";
        }
        if (!("latest_version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["latest_version"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["latest_prerelease"] = undefined;
        }
        if (!("update_available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["update_available"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["release_tag"] = undefined;
        }
        if (!("release_date" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_date"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("release_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["release_url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["changelog_url"] = undefined;
        }
        if (!("asset_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["asset_url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["asset_name"] = undefined;
        }
        if (!("asset_size" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["asset_size"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * AssetSHA256 is the release-API-provided asset digest when
             * published ("sha256:<hex>" normalized to bare hex). It is the
             * strongest checksum source for install verification.
             * @member
             * @type {string | undefined}
             */
            this["asset_sha256"] = undefined;
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["err"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UpdateInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UpdateInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UpdateInfo(/** @type {Partial<UpdateInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = HealthResult.createFrom;
