// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * CheckResult is the outcome of one individual probe.
 */
export class CheckResult {
    /**
     * Creates a new CheckResult instance.
     * @param {Partial<CheckResult>} [$$source = {}] - The source object to create the CheckResult.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("target" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["target"] = "";
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckResult(/** @type {Partial<CheckResult>} */($$parsedSource));
    }
}

/**
 * DNSDiagnosticReport is the outcome of ONE user-triggered run.
 */
export class DNSDiagnosticReport {
    /**
     * Creates a new DNSDiagnosticReport instance.
     * @param {Partial<DNSDiagnosticReport>} [$$source = {}] - The source object to create the DNSDiagnosticReport.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("resolvers" in $$source)) {
            /**
             * @member
             * @type {DNSResolverResult[]}
             */
            this["resolvers"] = [];
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["cancelled"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSDiagnosticReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSDiagnosticReport}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("resolvers" in $$parsedSource) {
            $$parsedSource["resolvers"] = $$createField1_0($$parsedSource["resolvers"]);
        }
        return new DNSDiagnosticReport(/** @type {Partial<DNSDiagnosticReport>} */($$parsedSource));
    }
}

/**
 * DNSFailureClass is the honest classification of one DNS failure
 * (§5.5) — never a single generic "internet failure".
 * @readonly
 * @enum {string}
 */
export const DNSFailureClass = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    DNSFailNone: "",
    DNSFailTimeout: "timeout",
    DNSFailRefused: "refused",
    DNSFailServfail: "servfail",
    DNSFailNXDomain: "nxdomain",
    DNSFailEmpty: "empty_answer",
    DNSFailMalformed: "malformed",
    DNSFailUnreachable: "resolver_unreachable",
    DNSFailCancelled: "cancelled",
    DNSFailInvalid: "invalid_target",
};

/**
 * DNSQueryResult is one (resolver, record type) row of evidence.
 */
export class DNSQueryResult {
    /**
     * Creates a new DNSQueryResult instance.
     * @param {Partial<DNSQueryResult>} [$$source = {}] - The source object to create the DNSQueryResult.
     */
    constructor($$source = {}) {
        if (!("resolver" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resolver"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * resolver address ("" = system)
             * @member
             * @type {string | undefined}
             */
            this["address"] = undefined;
        }
        if (!("transport" in $$source)) {
            /**
             * system | udp | tcp
             * @member
             * @type {string}
             */
            this["transport"] = "";
        }
        if (!("query_name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query_name"] = "";
        }
        if (!("record_type" in $$source)) {
            /**
             * @member
             * @type {DNSRecordType}
             */
            this["record_type"] = DNSRecordType.$zero;
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * DNS RCODE
             * @member
             * @type {number | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["measured"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["answer_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * bounded
             * @member
             * @type {string[] | undefined}
             */
            this["addresses"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {DNSFailureClass | undefined}
             */
            this["failure_class"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSQueryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSQueryResult}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addresses" in $$parsedSource) {
            $$parsedSource["addresses"] = $$createField10_0($$parsedSource["addresses"]);
        }
        return new DNSQueryResult(/** @type {Partial<DNSQueryResult>} */($$parsedSource));
    }
}

/**
 * DNSRecordType selects the query type of one diagnostic row.
 * @readonly
 * @enum {string}
 */
export const DNSRecordType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * The supported record types (§5.2: A + AAAA; additional diagnostic
     * records are deliberately NOT added — no unsafe complexity).
     */
    DNSTypeA: "A",
    DNSTypeAAAA: "AAAA",
};

/**
 * DNSResolverResult is one resolver's full row (A + AAAA).
 */
export class DNSResolverResult {
    /**
     * Creates a new DNSResolverResult instance.
     * @param {Partial<DNSResolverResult>} [$$source = {}] - The source object to create the DNSResolverResult.
     */
    constructor($$source = {}) {
        if (!("resolver" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["resolver"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * dominant transport
             * @member
             * @type {string | undefined}
             */
            this["transport"] = undefined;
        }
        if (!("ok" in $$source)) {
            /**
             * all queries OK
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("queries" in $$source)) {
            /**
             * @member
             * @type {DNSQueryResult[]}
             */
            this["queries"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * best successful
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSResolverResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DNSResolverResult}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("queries" in $$parsedSource) {
            $$parsedSource["queries"] = $$createField4_0($$parsedSource["queries"]);
        }
        return new DNSResolverResult(/** @type {Partial<DNSResolverResult>} */($$parsedSource));
    }
}

/**
 * Environment is the analyzed environment snapshot.
 */
export class Environment {
    /**
     * Creates a new Environment instance.
     * @param {Partial<Environment>} [$$source = {}] - The source object to create the Environment.
     */
    constructor($$source = {}) {
        if (!("signals" in $$source)) {
            /**
             * Signals are the observed signals (sorted, deduplicated).
             * @member
             * @type {EnvironmentSignal[]}
             */
            this["signals"] = [];
        }
        if (!("restricted" in $$source)) {
            /**
             * Restricted reports whether the evidence justifies escalated
             * discovery strategy (deeper source search, wider candidate
             * acceptance). It is a measured conclusion, never a censorship
             * claim.
             * @member
             * @type {boolean}
             */
            this["restricted"] = false;
        }
        if (!("deep_discovery_advised" in $$source)) {
            /**
             * DeepDiscoveryAdvised tells the discovery engine to escalate.
             * @member
             * @type {boolean}
             */
            this["deep_discovery_advised"] = false;
        }
        if (!("summary" in $$source)) {
            /**
             * Summary is the evidence-based, human-readable description.
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * Probes carries the raw probe evidence (already credential-free).
             * @member
             * @type {CheckResult[] | undefined}
             */
            this["probes"] = undefined;
        }
        if (!("analyzed_at" in $$source)) {
            /**
             * AnalyzedAt is the analysis timestamp.
             * @member
             * @type {string}
             */
            this["analyzed_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Environment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Environment}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType5;
        const $$createField4_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("signals" in $$parsedSource) {
            $$parsedSource["signals"] = $$createField0_0($$parsedSource["signals"]);
        }
        if ("probes" in $$parsedSource) {
            $$parsedSource["probes"] = $$createField4_0($$parsedSource["probes"]);
        }
        return new Environment(/** @type {Partial<Environment>} */($$parsedSource));
    }
}

/**
 * EnvironmentSignal is one evidence-based environment observation.
 * @readonly
 * @enum {string}
 */
export const EnvironmentSignal = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * SignalDirectOK: plain HTTP(S) connectivity works directly.
     */
    SignalDirectOK: "direct_ok",

    /**
     * SignalDNSFailure: name resolution fails while the network is up.
     */
    SignalDNSFailure: "dns_failure",

    /**
     * SignalHTTPFailure: TCP works but HTTP responses fail.
     */
    SignalHTTPFailure: "http_failure",

    /**
     * SignalTLSFailure: TLS handshakes fail against multiple
     * independent endpoints while plain TCP works — the strongest
     * interference evidence available to this layer.
     */
    SignalTLSFailure: "tls_failure",

    /**
     * SignalRepeatedTimeout: consecutive analyses observed end-to-end
     * timeouts (path black-holing).
     */
    SignalRepeatedTimeout: "repeated_timeout",

    /**
     * SignalCaptivePortal: a plain-HTTP 204 probe was hijacked
     * (redirect or content instead of 204).
     */
    SignalCaptivePortal: "captive_portal",

    /**
     * SignalProxyEnvironment: HTTP(S)_PROXY/ALL_PROXY is set in the
     * environment (a configured upstream the engine should respect
     * rather than fight).
     */
    SignalProxyEnvironment: "proxy_environment",

    /**
     * SignalUnstableConnectivity: measured latency variance across
     * HTTPS probes exceeds the instability threshold.
     */
    SignalUnstableConnectivity: "unstable_connectivity",

    /**
     * SignalRestrictedAccess: direct access to multiple independent
     * endpoints fails while the network itself is up.
     */
    SignalRestrictedAccess: "restricted_access",
};

/**
 * IdentityReport is the complete Network Identity result.
 */
export class IdentityReport {
    /**
     * Creates a new IdentityReport instance.
     * @param {Partial<IdentityReport>} [$$source = {}] - The source object to create the IdentityReport.
     */
    constructor($$source = {}) {
        if (!("local" in $$source)) {
            /**
             * @member
             * @type {LocalIdentity}
             */
            this["local"] = (new LocalIdentity());
        }
        if (!("public" in $$source)) {
            /**
             * @member
             * @type {PublicIdentity}
             */
            this["public"] = (new PublicIdentity());
        }
        if (!("metadata" in $$source)) {
            /**
             * @member
             * @type {NetworkMetadata}
             */
            this["metadata"] = (new NetworkMetadata());
        }
        if (!("path" in $$source)) {
            /**
             * direct | tunneled
             * @member
             * @type {ToolPath}
             */
            this["path"] = ToolPath.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["cancelled"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IdentityReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IdentityReport}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType9;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local" in $$parsedSource) {
            $$parsedSource["local"] = $$createField0_0($$parsedSource["local"]);
        }
        if ("public" in $$parsedSource) {
            $$parsedSource["public"] = $$createField1_0($$parsedSource["public"]);
        }
        if ("metadata" in $$parsedSource) {
            $$parsedSource["metadata"] = $$createField2_0($$parsedSource["metadata"]);
        }
        return new IdentityReport(/** @type {Partial<IdentityReport>} */($$parsedSource));
    }
}

/**
 * LocalAddress is one active local address with its interface.
 */
export class LocalAddress {
    /**
     * Creates a new LocalAddress instance.
     * @param {Partial<LocalAddress>} [$$source = {}] - The source object to create the LocalAddress.
     */
    constructor($$source = {}) {
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["interface"] = undefined;
        }
        if (!("family" in $$source)) {
            /**
             * ipv4 | ipv6
             * @member
             * @type {string}
             */
            this["family"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalAddress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalAddress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LocalAddress(/** @type {Partial<LocalAddress>} */($$parsedSource));
    }
}

/**
 * LocalIdentity is the measured local network identity.
 */
export class LocalIdentity {
    /**
     * Creates a new LocalIdentity instance.
     * @param {Partial<LocalIdentity>} [$$source = {}] - The source object to create the LocalIdentity.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * PrimaryIPv4 is the route-relevant local IPv4 — the source
             * address a connection to the public Internet would use (empty
             * when no IPv4 default route exists).
             * @member
             * @type {string | undefined}
             */
            this["primary_ipv4"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * PrimaryIPv6 is the route-relevant global IPv6 (empty when no
             * IPv6 default route exists — never fabricated).
             * @member
             * @type {string | undefined}
             */
            this["primary_ipv6"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Interface names the adapter that owns the primary address.
             * @member
             * @type {string | undefined}
             */
            this["interface"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Others lists additional active non-loopback addresses (bounded)
             * — the honest answer when several interfaces are up.
             * @member
             * @type {LocalAddress[] | undefined}
             */
            this["others"] = undefined;
        }
        if (!("measured" in $$source)) {
            /**
             * Measured marks that at least one address was actually observed.
             * @member
             * @type {boolean}
             */
            this["measured"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LocalIdentity instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LocalIdentity}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("others" in $$parsedSource) {
            $$parsedSource["others"] = $$createField3_0($$parsedSource["others"]);
        }
        return new LocalIdentity(/** @type {Partial<LocalIdentity>} */($$parsedSource));
    }
}

/**
 * NetworkMetadata is the measured ISP / network organization data.
 * Unavailable fields stay empty and Available stays false — nothing
 * is invented.
 */
export class NetworkMetadata {
    /**
     * Creates a new NetworkMetadata instance.
     * @param {Partial<NetworkMetadata>} [$$source = {}] - The source object to create the NetworkMetadata.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * ISP / org
             * @member
             * @type {string | undefined}
             */
            this["organization"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "AS15169"
             * @member
             * @type {string | undefined}
             */
            this["asn"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["country"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["region"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * metadata endpoint used
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NetworkMetadata instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NetworkMetadata}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NetworkMetadata(/** @type {Partial<NetworkMetadata>} */($$parsedSource));
    }
}

/**
 * PublicIdentity is the measured public (exit) identity.
 */
export class PublicIdentity {
    /**
     * Creates a new PublicIdentity instance.
     * @param {Partial<PublicIdentity>} [$$source = {}] - The source object to create the PublicIdentity.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * DirectIP is the public IPv4/IPv6 as seen on the DIRECT path.
             * @member
             * @type {string | undefined}
             */
            this["direct_ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TunnelIP is the public IP as seen THROUGH the active tunnel
             * (only measured when the caller supplied the tunnel dialer).
             * @member
             * @type {string | undefined}
             */
            this["tunnel_ip"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TunnelMatch compares direct and tunnel identities (meaningful
             * only when both were measured).
             * @member
             * @type {boolean | undefined}
             */
            this["tunnel_match"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Endpoint names the identity endpoint that answered (transparency).
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PublicIdentity instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PublicIdentity}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PublicIdentity(/** @type {Partial<PublicIdentity>} */($$parsedSource));
    }
}

/**
 * Report is the complete diagnostics snapshot.
 */
export class Report {
    /**
     * Creates a new Report instance.
     * @param {Partial<Report>} [$$source = {}] - The source object to create the Report.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("summary" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["summary"] = "";
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * best HTTPS latency
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target_used"] = undefined;
        }
        if (!("local_links" in $$source)) {
            /**
             * @member
             * @type {CheckResult[]}
             */
            this["local_links"] = [];
        }
        if (!("dns" in $$source)) {
            /**
             * @member
             * @type {CheckResult[]}
             */
            this["dns"] = [];
        }
        if (!("tcp" in $$source)) {
            /**
             * @member
             * @type {CheckResult[]}
             */
            this["tcp"] = [];
        }
        if (!("https" in $$source)) {
            /**
             * @member
             * @type {CheckResult[]}
             */
            this["https"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {CheckResult | null | undefined}
             */
            this["proxy"] = undefined;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cancelled"] = false;
        }
        if (!("target_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["target_count"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.9.8.5 staged evidence (§4): the ordered diagnostic ladder
             * (local link → local IP → DNS → TCP → TLS → HTTPS → captive
             * portal → direct Internet → tunnel Internet) with per-stage
             * status, measured latency and failure class — so a failure
             * surfaces as WHICH stage failed and why, never one generic
             * message. FailedStage names the first failed rung ("" when the
             * ladder is clean).
             * @member
             * @type {StageResult[] | undefined}
             */
            this["stages"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["failed_stage"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Report instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Report}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType7;
        const $$createField7_0 = $$createType7;
        const $$createField8_0 = $$createType7;
        const $$createField9_0 = $$createType7;
        const $$createField10_0 = $$createType13;
        const $$createField13_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("local_links" in $$parsedSource) {
            $$parsedSource["local_links"] = $$createField6_0($$parsedSource["local_links"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField7_0($$parsedSource["dns"]);
        }
        if ("tcp" in $$parsedSource) {
            $$parsedSource["tcp"] = $$createField8_0($$parsedSource["tcp"]);
        }
        if ("https" in $$parsedSource) {
            $$parsedSource["https"] = $$createField9_0($$parsedSource["https"]);
        }
        if ("proxy" in $$parsedSource) {
            $$parsedSource["proxy"] = $$createField10_0($$parsedSource["proxy"]);
        }
        if ("stages" in $$parsedSource) {
            $$parsedSource["stages"] = $$createField13_0($$parsedSource["stages"]);
        }
        return new Report(/** @type {Partial<Report>} */($$parsedSource));
    }
}

/**
 * StageID identifies one stage of the diagnostic ladder.
 * @readonly
 * @enum {string}
 */
export const StageID = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * The ladder, in order.
     */
    StageLocalLink: "local_link",
    StageLocalIP: "local_ip",
    StageDNS: "dns",
    StageTCP: "tcp",
    StageTLS: "tls",
    StageHTTPS: "https",
    StageCaptive: "captive_portal",
    StageDirect: "direct_internet",
    StageTunnel: "tunnel_internet",
};

/**
 * StageResult is the structured evidence of ONE ladder stage.
 */
export class StageResult {
    /**
     * Creates a new StageResult instance.
     * @param {Partial<StageResult>} [$$source = {}] - The source object to create the StageResult.
     */
    constructor($$source = {}) {
        if (!("stage" in $$source)) {
            /**
             * @member
             * @type {StageID}
             */
            this["stage"] = StageID.$zero;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {StageStatus}
             */
            this["status"] = StageStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["measured"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["detail"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["failure_class"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StageResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StageResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StageResult(/** @type {Partial<StageResult>} */($$parsedSource));
    }
}

/**
 * StageStatus is the outcome of one ladder stage.
 * @readonly
 * @enum {string}
 */
export const StageStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * StageOK: the stage succeeded (measured).
     */
    StageOK: "ok",

    /**
     * StageFailed: the stage was checked and failed.
     */
    StageFailed: "failed",

    /**
     * StageSkipped: the stage could not be meaningfully evaluated
     * because an earlier stage already failed (e.g. captive portal
     * cannot be judged when HTTPS is dead).
     */
    StageSkipped: "skipped",

    /**
     * StageNotChecked: the stage was not part of this run (e.g. the
     * tunnel stage without a proxy address).
     */
    StageNotChecked: "not_checked",
};

/**
 * State is the classified overall connectivity state.
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * StateNoInternet: no working local network / no TCP anywhere.
     */
    StateNoInternet: "no_internet",

    /**
     * StateDNSFailure: local network up, DNS resolution failing.
     */
    StateDNSFailure: "dns_failure",

    /**
     * StateHTTPSFailure: TCP works, HTTPS requests fail (blocking /
     * captive portal / TLS interference).
     */
    StateHTTPSFailure: "https_failure",

    /**
     * StateHighLatency: everything works but slowly.
     */
    StateHighLatency: "high_latency",

    /**
     * StateOK: internet working normally.
     */
    StateOK: "ok",

    /**
     * StateProxyOnly: direct internet blocked, but the probe through
     * the configured proxy/core succeeded.
     */
    StateProxyOnly: "proxy_only",

    /**
     * StateCoreNoInternet: the core is connected but external
     * connectivity through it fails.
     */
    StateCoreNoInternet: "core_no_internet",
};

/**
 * ToolID identifies one user-triggered network tool.
 * @readonly
 * @enum {string}
 */
export const ToolID = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * The tool catalogue (§6). Every entry is user-triggered only.
     *
     * Connectivity.
     * aggregate connectivity check (the classic Report)
     */
    ToolInternet: "internet",

    /**
     * resolve a name through a resolver
     */
    ToolDNS: "dns",

    /**
     * raw TCP reachability + RTT
     */
    ToolTCP: "tcp",

    /**
     * TCP + TLS handshake
     */
    ToolTLS: "tls",

    /**
     * full HTTP(S) GET with redirects/size caps
     */
    ToolHTTPS: "https",

    /**
     * Protocol.
     * HTTP proxy CONNECT test
     */
    ToolHTTPConnect: "http_connect",

    /**
     * SOCKS5 CONNECT test
     */
    ToolSOCKS5: "socks5",

    /**
     * WebSocket upgrade handshake
     */
    ToolWebSocket: "websocket",

    /**
     * UDP payload round trip (DNS query)
     */
    ToolUDP: "udp",

    /**
     * QUIC — honestly reported below
     */
    ToolQUIC: "quic",

    /**
     * Path.
     * ICMP TTL walk (privilege-gated)
     */
    ToolTraceroute: "traceroute",

    /**
     * unfragmented payload ladder
     */
    ToolPathMTU: "path_mtu",

    /**
     * captive-portal detection
     */
    ToolCaptivePortal: "captive_portal",

    /**
     * Identity.
     * exit IP, direct vs tunnel
     */
    ToolPublicIP: "public_ip",

    /**
     * Tunnel diagnostics.
     * active provider truth
     */
    ToolTunnelDiagnostics: "tunnel_diagnostics",
};

/**
 * ToolCatalogue returns the catalogue with labels for the UI.
 */
export class ToolInfo {
    /**
     * Creates a new ToolInfo instance.
     * @param {Partial<ToolInfo>} [$$source = {}] - The source object to create the ToolInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {ToolID}
             */
            this["id"] = ToolID.$zero;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("group" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["group"] = "";
        }
        if (!("takes_target" in $$source)) {
            /**
             * user may supply a custom target
             * @member
             * @type {boolean}
             */
            this["takes_target"] = false;
        }
        if (!("timeout_ms" in $$source)) {
            /**
             * default timeout
             * @member
             * @type {number}
             */
            this["timeout_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ToolInfo(/** @type {Partial<ToolInfo>} */($$parsedSource));
    }
}

/**
 * ToolMeasurement is the structured, tool-specific measurement.
 * Millisecond projections follow the v0.9.8.1 canonical semantics
 * (engine/tester/latency.go rules R3/R4): Measured is the authority;
 * 0 ms + Measured = sub-millisecond.
 */
export class ToolMeasurement {
    /**
     * Creates a new ToolMeasurement instance.
     * @param {Partial<ToolMeasurement>} [$$source = {}] - The source object to create the ToolMeasurement.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * LatencyMS is the measured round-trip (dial, handshake or full
             * request, as documented per tool). Sub-ms reads 0 — see Measured.
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Measured is the authoritative measurement flag.
             * @member
             * @type {boolean | undefined}
             */
            this["measured"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * SubMS marks a measured sub-millisecond round trip ("< 1 ms").
             * @member
             * @type {boolean | undefined}
             */
            this["sub_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Status is the protocol-level status (HTTP status code, SOCKS5
             * reply code, DNS response code).
             * @member
             * @type {number | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Bytes received (bounded by the safety cap).
             * @member
             * @type {number | undefined}
             */
            this["bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Addresses are resolved answers (DNS tool) or exit IPs
             * (public_ip tool) — IP literals only, never credentials.
             * @member
             * @type {string[] | undefined}
             */
            this["addresses"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * AddressCount avoids leaking large answer sets in the UI.
             * @member
             * @type {number | undefined}
             */
            this["address_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TLSVersion / Cipher describe a negotiated TLS session.
             * @member
             * @type {string | undefined}
             */
            this["tls_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cipher"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * HopCount / Hops carry traceroute results (hop IPs).
             * @member
             * @type {number | undefined}
             */
            this["hop_count"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["hops"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * MTUBytes is the verified unfragmented payload size (path_mtu).
             * @member
             * @type {number | undefined}
             */
            this["mtu_bytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ExitIPDirect / ExitIPTunnel / ExitIPMatch answer the public_ip
             * identity questions (direct vs active tunnel).
             * @member
             * @type {string | undefined}
             */
            this["exit_ip_direct"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["exit_ip_tunnel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["exit_ip_match"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * CaptiveDetected / CaptiveRedirect mark portal findings.
             * @member
             * @type {boolean | undefined}
             */
            this["captive_detected"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["captive_redirect"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Tunnel carries the active-tunnel truth (tunnel_diagnostics).
             * @member
             * @type {TunnelSnapshot | null | undefined}
             */
            this["tunnel"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Probes counts the bounded sub-probes a multi-target tool ran.
             * @member
             * @type {number | undefined}
             */
            this["probes"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolMeasurement instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolMeasurement}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        const $$createField10_0 = $$createType2;
        const $$createField17_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("addresses" in $$parsedSource) {
            $$parsedSource["addresses"] = $$createField5_0($$parsedSource["addresses"]);
        }
        if ("hops" in $$parsedSource) {
            $$parsedSource["hops"] = $$createField10_0($$parsedSource["hops"]);
        }
        if ("tunnel" in $$parsedSource) {
            $$parsedSource["tunnel"] = $$createField17_0($$parsedSource["tunnel"]);
        }
        return new ToolMeasurement(/** @type {Partial<ToolMeasurement>} */($$parsedSource));
    }
}

/**
 * ToolPath says whether a tool ran direct or through the active
 * tunnel.
 * @readonly
 * @enum {string}
 */
export const ToolPath = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    PathDirect: "direct",
    PathTunneled: "tunneled",
};

/**
 * ToolResult is the complete structured outcome of one tool run.
 */
export class ToolResult {
    /**
     * Creates a new ToolResult instance.
     * @param {Partial<ToolResult>} [$$source = {}] - The source object to create the ToolResult.
     */
    constructor($$source = {}) {
        if (!("tool_id" in $$source)) {
            /**
             * @member
             * @type {ToolID}
             */
            this["tool_id"] = ToolID.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["target"] = undefined;
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("finished_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["finished_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {ToolStatus}
             */
            this["status"] = ToolStatus.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * tcp/udp/tls/https/icmp/ws/socks5/http-connect
             * @member
             * @type {string | undefined}
             */
            this["transport"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ToolPath | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "" = direct/system
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (!("measurement" in $$source)) {
            /**
             * @member
             * @type {ToolMeasurement}
             */
            this["measurement"] = (new ToolMeasurement());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: string } | undefined}
             */
            this["details"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * DNS carries the structured DNS-diagnostic evidence (§5) when
             * this run is a DNS diagnostic (v0.9.8.5) — per-resolver rows
             * with per-record-type results, transports and failure classes.
             * @member
             * @type {DNSDiagnosticReport | null | undefined}
             */
            this["dns"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ToolResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ToolResult}
     */
    static createFrom($$source = {}) {
        const $$createField9_0 = $$createType18;
        const $$createField11_0 = $$createType19;
        const $$createField12_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("measurement" in $$parsedSource) {
            $$parsedSource["measurement"] = $$createField9_0($$parsedSource["measurement"]);
        }
        if ("details" in $$parsedSource) {
            $$parsedSource["details"] = $$createField11_0($$parsedSource["details"]);
        }
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField12_0($$parsedSource["dns"]);
        }
        return new ToolResult(/** @type {Partial<ToolResult>} */($$parsedSource));
    }
}

/**
 * ToolStatus is the structured outcome state of one tool run.
 * @readonly
 * @enum {string}
 */
export const ToolStatus = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ToolStatusOK: the tool ran and succeeded.
     */
    ToolStatusOK: "ok",

    /**
     * ToolStatusFailed: the tool ran and failed (refused, reset,
     * protocol error, HTTP >= 400 ...).
     */
    ToolStatusFailed: "failed",

    /**
     * ToolStatusTimeout: the tool hit its configured deadline.
     */
    ToolStatusTimeout: "timeout",

    /**
     * ToolStatusCancelled: the caller cancelled the context.
     */
    ToolStatusCancelled: "cancelled",

    /**
     * ToolStatusInvalid: the safety layer rejected the target before
     * any bytes left the machine.
     */
    ToolStatusInvalid: "invalid_target",

    /**
     * ToolStatusUnsupported: the capability is honestly not available
     * in this build / on this platform / without privileges. Nothing
     * is claimed that was not verified.
     */
    ToolStatusUnsupported: "unsupported",
};

/**
 * TunnelSnapshot is the live, measured truth about the active tunnel
 * supplied by the caller (never fabricated by the tools layer).
 */
export class TunnelSnapshot {
    /**
     * Creates a new TunnelSnapshot instance.
     * @param {Partial<TunnelSnapshot>} [$$source = {}] - The source object to create the TunnelSnapshot.
     */
    constructor($$source = {}) {
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * "xray" / "v2ray" / "sing-box" / "tor" / "psiphon"
             * @member
             * @type {string | undefined}
             */
            this["provider"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * local SOCKS host:port
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["healthy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TunnelSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TunnelSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TunnelSnapshot(/** @type {Partial<TunnelSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = DNSResolverResult.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = DNSQueryResult.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = CheckResult.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = LocalIdentity.createFrom;
const $$createType9 = PublicIdentity.createFrom;
const $$createType10 = NetworkMetadata.createFrom;
const $$createType11 = LocalAddress.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $Create.Nullable($$createType6);
const $$createType14 = StageResult.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = TunnelSnapshot.createFrom;
const $$createType17 = $Create.Nullable($$createType16);
const $$createType18 = ToolMeasurement.createFrom;
const $$createType19 = $Create.Map($Create.Any, $Create.Any);
const $$createType20 = DNSDiagnosticReport.createFrom;
const $$createType21 = $Create.Nullable($$createType20);
