// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * FailureCategory classifies why a test failed. Used by the UI to
 * render failure chips and by the re-test policy to decide whether
 * to retry.
 * @readonly
 * @enum {string}
 */
export const FailureCategory = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    FailureNone: "",
    FailureNetwork: "network",
    FailureAuth: "auth",
    FailureProtocol: "protocol",
    FailureConfig: "config",
    FailureBackendDown: "backend_down",
    FailureBackendReject: "backend_reject",
    FailureTimeout: "timeout",
    FailureCancelled: "cancelled",
    FailureUnknown: "unknown",
};

/**
 * Mode selects the testing mode. Each mode presets Concurrency,
 * Timeout, MaxAttempts and MeasurementSamples.
 * @readonly
 * @enum {string}
 */
export const Mode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ModeQuick: 2 workers, 5s timeout, 1 attempt. For "is this
     * config alive?" checks.
     */
    ModeQuick: "quick",

    /**
     * ModeBalanced: default. 4 workers, 10s timeout, 2 attempts.
     */
    ModeBalanced: "balanced",

    /**
     * ModeDeep: 2 workers, 20s timeout, 3 attempts, 3 measurements
     * averaged. For "verify this config thoroughly".
     */
    ModeDeep: "deep",

    /**
     * ModeRetestFailed: only re-test configs whose last result was
     * failed or timed_out. 4 workers, 10s timeout, 2 attempts.
     */
    ModeRetestFailed: "retest_failed",

    /**
     * ModeTestAll: queue every untested config. Inherits Balanced
     * settings.
     */
    ModeTestAll: "test_all",

    /**
     * ModeTestSelected: queue the user's selection. Inherits Balanced
     * settings.
     */
    ModeTestSelected: "test_selected",

    /**
     * ModeContinuous: background queue that keeps working configs
     * fresh and re-tests stale ones. 2 workers, 10s timeout, 1
     * attempt. Runs until stopped.
     */
    ModeContinuous: "continuous",
};

/**
 * Result is the outcome of one test.
 */
export class Result {
    /**
     * Creates a new Result instance.
     * @param {Partial<Result>} [$$source = {}] - The source object to create the Result.
     */
    constructor($$source = {}) {
        if (!("working" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["working"] = false;
        }
        if (!("latency" in $$source)) {
            /**
             * @member
             * @type {time$0.Duration}
             */
            this["latency"] = time$0.Duration.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * Measured is the authoritative measurement flag (v0.9.8.1,
             * engine/tester/latency.go rule R3): Latency/PingMS == 0 with
             * Measured == true is a measured sub-millisecond round trip.
             * @member
             * @type {boolean | undefined}
             */
            this["measured"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["backend"] = undefined;
        }
        if (!("tested_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["tested_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {FailureCategory | undefined}
             */
            this["failure_category"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * --- v0.9.0: honest test reporting (§4) ---
             * @member
             * @type {string | undefined}
             */
            this["protocol"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["ping_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["duration_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["quality"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Result instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Result}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Result(/** @type {Partial<Result>} */($$parsedSource));
    }
}

/**
 * Stats is the runtime statistics block, surfaced to the UI.
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("queue_depth" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queue_depth"] = 0;
        }
        if (!("active_workers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["active_workers"] = 0;
        }
        if (!("total_enqueued" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_enqueued"] = 0;
        }
        if (!("total_completed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_completed"] = 0;
        }
        if (!("total_passed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_passed"] = 0;
        }
        if (!("total_failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_failed"] = 0;
        }
        if (!("total_timed_out" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_timed_out"] = 0;
        }
        if (!("total_cancelled" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total_cancelled"] = 0;
        }
        if (!("tests_per_sec" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tests_per_sec"] = 0;
        }
        if (!("avg_duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_duration_ms"] = 0;
        }
        if (!("per_backend" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: number }}
             */
            this["per_backend"] = {};
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["started_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.9.0 (§5): measured-latency aggregates for the live
             * progress panel. 0 = no successful measurement yet.
             * @member
             * @type {number | undefined}
             */
            this["avg_latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["fastest_latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["slowest_latency_ms"] = undefined;
        }
        if (!("active_cores" in $$source)) {
            /**
             * v0.9.7 (§13/§14): temporary core-process accounting for the UI.
             * ActiveCores is the number of temporary protocol-core processes
             * alive right now (≤ CoreProbeConcurrency); CoreProbeConcurrency
             * is the effective cap.
             * @member
             * @type {number}
             */
            this["active_cores"] = 0;
        }
        if (!("core_probe_concurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["core_probe_concurrency"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("per_backend" in $$parsedSource) {
            $$parsedSource["per_backend"] = $$createField10_0($$parsedSource["per_backend"]);
        }
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

/**
 * TaskSnapshot is a copy of a Task suitable for returning to the UI
 * (no embedded mutex). It is JSON-marshallable for the Wails
 * bindings.
 */
export class TaskSnapshot {
    /**
     * Creates a new TaskSnapshot instance.
     * @param {Partial<TaskSnapshot>} [$$source = {}] - The source object to create the TaskSnapshot.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("protocol" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["protocol"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["backends"] = undefined;
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (!("attempt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["attempt"] = 0;
        }
        if (!("max_attempts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["max_attempts"] = 0;
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["deadline"] = undefined;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {TaskState}
             */
            this["state"] = TaskState.$zero;
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {Result}
             */
            this["result"] = (new Result());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TaskSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        const $$createField11_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backends" in $$parsedSource) {
            $$parsedSource["backends"] = $$createField3_0($$parsedSource["backends"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField11_0($$parsedSource["result"]);
        }
        return new TaskSnapshot(/** @type {Partial<TaskSnapshot>} */($$parsedSource));
    }
}

/**
 * TaskState is the lifecycle state of one queued test.
 * @readonly
 * @enum {string}
 */
export const TaskState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * StateQueued: task is in the queue waiting for a worker.
     */
    StateQueued: "queued",

    /**
     * StatePreparing: worker picked up the task, building runtime config.
     */
    StatePreparing: "preparing",

    /**
     * StateTesting: core process spawned, readiness probe in flight.
     */
    StateTesting: "testing",

    /**
     * StateMeasuring: core is ready, latency probe in flight.
     */
    StateMeasuring: "measuring",

    /**
     * StatePassed: test completed successfully.
     */
    StatePassed: "passed",

    /**
     * StateFailed: test completed with a non-timeout failure.
     */
    StateFailed: "failed",

    /**
     * StateTimedOut: test exceeded its per-config timeout.
     */
    StateTimedOut: "timed_out",

    /**
     * StateCancelled: task was cancelled before completion.
     */
    StateCancelled: "cancelled",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = Result.createFrom;
