// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Stats is the runtime statistics block for one source, returned to
 * the UI in the source registry snapshot. It is derived from the
 * Source metadata fields above; keeping it as a separate struct lets
 * the UI bind a stable shape even when Source grows.
 * 
 * v0.13.0 freshness contract: LastSuccessfulFetch / LastFailure are
 * POINTERS. A Go zero time.Time serialises as "0001-01-01T00:00:00Z"
 * (encoding/json never omits a struct), which the UI converted into
 * an absurd "739889d ago" age. A nil pointer OMITS the JSON field, so
 * a never-fetched source reaches the UI as an absent timestamp — the
 * UI renders "Never fetched" — while valid times stay exact.
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("region" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["region"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (!("trust" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["trust"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_successful_fetch"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["last_failure"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_failure_reason"] = undefined;
        }
        if (!("config_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["config_count"] = 0;
        }
        if (!("working_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["working_count"] = 0;
        }
        if (!("average_latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["average_latency_ms"] = 0;
        }
        if (!("reliability_score" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["reliability_score"] = 0;
        }
        if (!("fetch_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetch_count"] = 0;
        }
        if (!("success_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["success_count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}
