// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * AppService exposes lifecycle and aggregate state.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CacheStats returns cache layer statistics.
 * @returns {$CancellablePromise<$models.CacheStats>}
 */
export function CacheStats() {
    return $Call.ByID(2904626025).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ClearCaches drops all cached data (does not touch stored records).
 * @returns {$CancellablePromise<void>}
 */
export function ClearCaches() {
    return $Call.ByID(1912484394);
}

/**
 * State returns the application state snapshot.
 * @returns {$CancellablePromise<$models.AppState>}
 */
export function State() {
    return $Call.ByID(1052657221).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.CacheStats.createFrom;
const $$createType1 = $models.AppState.createFrom;
