// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionService exposes favorites and groups to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddToUserGroup adds a configuration to a group (idempotent).
 * @param {string} groupID
 * @param {string} configID
 * @returns {$CancellablePromise<void>}
 */
export function AddToUserGroup(groupID, configID) {
    return $Call.ByID(3598108571, groupID, configID);
}

/**
 * CreateUserGroup adds a named group and persists it.
 * @param {string} name
 * @returns {$CancellablePromise<$models.UserGroupView>}
 */
export function CreateUserGroup(name) {
    return $Call.ByID(4205493491, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteUserGroup removes a group (configurations are untouched —
 * they live in the store, not the group).
 * @param {string} groupID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteUserGroup(groupID) {
    return $Call.ByID(2261608410, groupID);
}

/**
 * Favorites returns the ordered favorite configuration IDs.
 * @returns {$CancellablePromise<string[]>}
 */
export function Favorites() {
    return $Call.ByID(45155240).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GroupMembers returns the configuration IDs of one user group.
 * @param {string} groupID
 * @returns {$CancellablePromise<string[]>}
 */
export function GroupMembers(groupID) {
    return $Call.ByID(641439845, groupID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GroupsOverview returns the built-in evidence groups with live
 * counts plus the user groups. Built-in counts are computed from the
 * store's real records in ONE bounded scan (the same bound the
 * ranking engine uses) — never from invented scores.
 * @returns {$CancellablePromise<$models.GroupsOverview | null>}
 */
export function GroupsOverview() {
    return $Call.ByID(414421188).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * IsFavorite reports whether a configuration is a favorite.
 * @param {string} configID
 * @returns {$CancellablePromise<boolean>}
 */
export function IsFavorite(configID) {
    return $Call.ByID(2129804087, configID);
}

/**
 * RemoveFromUserGroup removes a configuration from a group
 * (idempotent; removing a missing member succeeds).
 * @param {string} groupID
 * @param {string} configID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveFromUserGroup(groupID, configID) {
    return $Call.ByID(4177556675, groupID, configID);
}

/**
 * RenameUserGroup renames a group.
 * @param {string} groupID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameUserGroup(groupID, name) {
    return $Call.ByID(1651871193, groupID, name);
}

/**
 * ToggleFavorite adds or removes a favorite and persists the sidecar.
 * The returned bool is the NEW state. Favorites never bypass testing
 * or verification — they are a UI affordance only.
 * @param {string} configID
 * @returns {$CancellablePromise<boolean>}
 */
export function ToggleFavorite(configID) {
    return $Call.ByID(862371431, configID);
}

/**
 * UserGroups lists the user-defined groups with live member counts.
 * @returns {$CancellablePromise<$models.UserGroupView[]>}
 */
export function UserGroups() {
    return $Call.ByID(2817798640).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.UserGroupView.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = $models.GroupsOverview.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
