// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ConnectionService exposes the protocol-core connection lifecycle.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $connection from "../connection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $core from "../core/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $config from "../config/models.js";

/**
 * Backends lists the registered protocol-core backends with their
 * availability state and verified reference versions.
 * @returns {$CancellablePromise<$models.BackendView[]>}
 */
export function Backends() {
    return $Call.ByID(2779658394).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * RefreshBackends re-runs executable discovery synchronously.
 * @returns {$CancellablePromise<$models.BackendView[]>}
 */
export function RefreshBackends() {
    return $Call.ByID(2762070079).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ConnectionState returns the connection state machine snapshot.
 * @returns {$CancellablePromise<$connection.Snapshot>}
 */
export function ConnectionState() {
    return $Call.ByID(1928655112).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Connect establishes the tunnel for a stored configuration.
 * @param {string} configID
 * @returns {$CancellablePromise<$connection.Snapshot>}
 */
export function Connect(configID) {
    return $Call.ByID(2469079379, configID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ConnectConfig establishes the tunnel for an ad-hoc configuration.
 * @param {$config.Config} cfg
 * @returns {$CancellablePromise<$connection.Snapshot>}
 */
export function ConnectConfig(cfg) {
    return $Call.ByID(2034769009, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Disconnect tears the session down.
 * @returns {$CancellablePromise<$connection.Snapshot>}
 */
export function Disconnect() {
    return $Call.ByID(922028949).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Reconnect re-establishes the last session.
 * @returns {$CancellablePromise<$connection.Snapshot>}
 */
export function Reconnect() {
    return $Call.ByID(1134772884).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Health measures the active session.
 * @returns {$CancellablePromise<$core.HealthReport>}
 */
export function Health() {
    return $Call.ByID(4221796969).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ConfigDetails renders the details view for one stored
 * configuration (credentials redacted by default).
 * @param {string} configID
 * @returns {$CancellablePromise<$models.ConfigDetail | null>}
 */
export function ConfigDetails(configID) {
    return $Call.ByID(2939126541, configID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $Create.Array($models.BackendView.createFrom);
const $$createType1 = $connection.Snapshot.createFrom;
const $$createType2 = $core.HealthReport.createFrom;
const $$createType3 = $Create.Nullable($models.ConfigDetail.createFrom);
