// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CoreService exposes the Managed Core Manager to the UI. Every method
 * is a thin wrapper around the corresponding coremgr.Manager method
 * so the Wails binding layer can expose them as a namespaced API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as coremgr$0 from "../coremgr/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CheckAllForUpdates queries every core in parallel.
 * @returns {$CancellablePromise<coremgr$0.UpdateInfo[]>}
 */
export function CheckAllForUpdates() {
    return $Call.ByID(2672113496).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CheckForUpdates queries the upstream release API for one core.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<coremgr$0.UpdateInfo>}
 */
export function CheckForUpdates(name) {
    return $Call.ByID(4271600323, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Disable marks a core as disabled.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<void>}
 */
export function Disable(name) {
    return $Call.ByID(99323712, name);
}

/**
 * Enable re-activates a disabled core.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<void>}
 */
export function Enable(name) {
    return $Call.ByID(2975970531, name);
}

/**
 * HealthCheck re-runs the smoke test for one core.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<coremgr$0.HealthResult>}
 */
export function HealthCheck(name) {
    return $Call.ByID(3050447506, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * HealthCheckAll runs smoke tests for every core in parallel.
 * @returns {$CancellablePromise<{ [_ in coremgr$0.CoreName]?: coremgr$0.HealthResult }>}
 */
export function HealthCheckAll() {
    return $Call.ByID(314680457).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Info returns the manifest for one core.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<coremgr$0.Manifest>}
 */
export function Info(name) {
    return $Call.ByID(2971713304, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Install downloads and activates the latest stable release for one
 * core. This is a long-running operation; progress is delivered via
 * the freeiran:coreprogress event.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<void>}
 */
export function Install(name) {
    return $Call.ByID(3978262431, name);
}

/**
 * LifecycleInfo is the UI projection of one core: the persisted
 * manifest plus the live runtime view (registry availability) and a
 * human-readable failure explanation. The runtime state covers the
 * Starting/Running/Stopping/Failed half of the lifecycle that does
 * not persist across restarts.
 * @returns {$CancellablePromise<$models.CoreLifecycleView[]>}
 */
export function LifecycleInfo() {
    return $Call.ByID(2500551292).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * List returns every managed core's manifest.
 * @returns {$CancellablePromise<coremgr$0.Manifest[]>}
 */
export function List() {
    return $Call.ByID(83371372).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Reinstall removes every local artifact of a core and performs a
 * fresh install from upstream.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<void>}
 */
export function Reinstall(name) {
    return $Call.ByID(2738887680, name);
}

/**
 * Repair tries to fix a broken core: rollback first, fresh install
 * second. Discovery is refreshed afterwards so a repaired binary is
 * immediately usable.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<void>}
 */
export function Repair(name) {
    return $Call.ByID(3147496593, name);
}

/**
 * Rollback reverts one core to its previously retained version.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<void>}
 */
export function Rollback(name) {
    return $Call.ByID(3605962432, name);
}

/**
 * SetChannel changes the release channel.
 * @param {coremgr$0.CoreName} name
 * @param {coremgr$0.Channel} channel
 * @returns {$CancellablePromise<void>}
 */
export function SetChannel(name, channel) {
    return $Call.ByID(3274127599, name, channel);
}

/**
 * Uninstall removes one core and its manifest.
 * @param {coremgr$0.CoreName} name
 * @returns {$CancellablePromise<void>}
 */
export function Uninstall(name) {
    return $Call.ByID(3664489838, name);
}

/**
 * UpdateAll checks every core for updates and installs what is
 * newer. Returns a per-core outcome map.
 * @returns {$CancellablePromise<{ [_ in coremgr$0.CoreName]?: any }>}
 */
export function UpdateAll() {
    return $Call.ByID(2501687524).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

// Private type creation functions
const $$createType0 = coremgr$0.UpdateInfo.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = coremgr$0.HealthResult.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = coremgr$0.Manifest.createFrom;
const $$createType5 = $models.CoreLifecycleView.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $Create.Array($$createType4);
const $$createType8 = $Create.Map($Create.Any, $Create.Any);
