// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataService exposes stored configurations to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns one configuration by fingerprint.
 * @param {string} id
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig(id) {
    return $Call.ByID(3324103243, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetConfigOrder returns the stored order (may be empty).
 * @returns {$CancellablePromise<string[]>}
 */
export function GetConfigOrder() {
    return $Call.ByID(2328885517).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ListConfigs returns a page of configurations ordered by fingerprint.
 * Pages are virtualized in the UI; only the requested window is
 * decoded and materialised.
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ConfigPage | null>}
 */
export function ListConfigs(offset, limit) {
    return $Call.ByID(962507682, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * ListConfigsFiltered returns a sorted, filtered page of
 * configurations. Filtering happens engine-side; only the requested
 * window crosses the service boundary.
 * @param {$models.ConfigFilter} filter
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ConfigPage | null>}
 */
export function ListConfigsFiltered(filter, offset, limit) {
    return $Call.ByID(3482301325, filter, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * MoveConfig moves one configuration (by stable ID) to the given
 * zero-based index within the complete ordered collection. It works
 * for first→last, last→first, middle moves and repeated moves, and it
 * never touches the underlying configurations — only their order.
 * @param {string} id
 * @param {number} toIndex
 * @returns {$CancellablePromise<void>}
 */
export function MoveConfig(id, toIndex) {
    return $Call.ByID(4459056, id, toIndex);
}

/**
 * SearchConfigs returns configurations matching a case-insensitive
 * substring across address, name and protocol. Results are bounded.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<config$0.Config[]>}
 */
export function SearchConfigs(query, limit) {
    return $Call.ByID(3765505226, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * SetConfigOrder persists the complete ordered collection of stable
 * configuration IDs. IDs missing from the current store are pruned on
 * the next apply; IDs missing from the provided list are appended in
 * store order (the list the caller sends is authoritative).
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function SetConfigOrder(ids) {
    return $Call.ByID(1065506393, ids);
}

/**
 * TestConfig enqueues ONE configuration through the app's ONE
 * authoritative testing engine (testqueue → worker → tester →
 * persistence) and returns promptly with the config's current
 * snapshot. Duplicate requests collapse into the queued task. The
 * result is persisted by the queue's own result path; the UI observes
 * it incrementally (no full-list refresh).
 * @param {string} id
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function TestConfig(id) {
    return $Call.ByID(2359709017, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($Create.Any);
const $$createType3 = $models.ConfigPage.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = $Create.Array($$createType0);
