// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DataService exposes stored configurations to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConfig returns one configuration by fingerprint.
 * @param {string} id
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function GetConfig(id) {
    return $Call.ByID(3324103243, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * ListConfigs returns a page of configurations ordered by fingerprint.
 * Pages are virtualized in the UI; only the requested window is
 * decoded and materialised.
 * @param {number} offset
 * @param {number} limit
 * @returns {$CancellablePromise<$models.ConfigPage | null>}
 */
export function ListConfigs(offset, limit) {
    return $Call.ByID(962507682, offset, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * SearchConfigs returns configurations matching a case-insensitive
 * substring across address, name and protocol. Results are bounded.
 * @param {string} query
 * @param {number} limit
 * @returns {$CancellablePromise<config$0.Config[]>}
 */
export function SearchConfigs(query, limit) {
    return $Call.ByID(3765505226, query, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * TestConfig runs a reachability test and persists the outcome.
 * @param {string} id
 * @returns {$CancellablePromise<config$0.Config | null>}
 */
export function TestConfig(id) {
    return $Call.ByID(2359709017, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = config$0.Config.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ConfigPage.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = $Create.Array($$createType0);
