// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiagnosticsService exposes local-only performance diagnostics.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metrics$0 from "../metrics/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "../../system/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * BuildDiagnosticReport assembles the sanitized report.
 * @returns {$CancellablePromise<$models.DiagnosticReport | null>}
 */
export function BuildDiagnosticReport() {
    return $Call.ByID(968569880).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Cores lists discovered protocol-core binaries.
 * @returns {$CancellablePromise<system$0.CoreBinary[]>}
 */
export function Cores() {
    return $Call.ByID(2280326489).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * DeveloperInfo assembles the snapshot. Every accessor is best-effort:
 * a lazy subsystem that has not started yet simply reports zeros.
 * @returns {$CancellablePromise<$models.DeveloperInfoView>}
 */
export function DeveloperInfo() {
    return $Call.ByID(37667759).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Memory returns the Memory Booster 2.0 report: pressure state,
 * Go/native memory picture, adaptive settings and the subsystem
 * measurements that produced them. Every value is a live measurement
 * or a live controller state — nothing is synthetic.
 * @returns {$CancellablePromise<$models.MemorySnapshot>}
 */
export function Memory() {
    return $Call.ByID(3556273300).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Metrics returns the engine performance counters.
 * @returns {$CancellablePromise<metrics$0.Snapshot>}
 */
export function Metrics() {
    return $Call.ByID(3687510332).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * StoreDiagnostics returns the deep storage-subsystem report: open
 * file handles, cache hit rates, memtable pressure, WAL size, flush
 * and compaction timings. Every value is a live measurement.
 * @returns {$CancellablePromise<store$0.Diagnostics>}
 */
export function StoreDiagnostics() {
    return $Call.ByID(902993624).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * SystemInfo returns platform information.
 * @returns {$CancellablePromise<system$0.Info>}
 */
export function SystemInfo() {
    return $Call.ByID(1223730458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * Version returns the application version string.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(2987005461);
}

// Private type creation functions
const $$createType0 = $models.DiagnosticReport.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = system$0.CoreBinary.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.DeveloperInfoView.createFrom;
const $$createType5 = $models.MemorySnapshot.createFrom;
const $$createType6 = metrics$0.Snapshot.createFrom;
const $$createType7 = store$0.Diagnostics.createFrom;
const $$createType8 = system$0.Info.createFrom;
