// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiagnosticsService exposes local-only performance diagnostics.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as metrics$0 from "../metrics/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as system$0 from "../../system/models.js";

/**
 * Cores lists discovered protocol-core binaries.
 * @returns {$CancellablePromise<system$0.CoreBinary[]>}
 */
export function Cores() {
    return $Call.ByID(2280326489).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Metrics returns the engine performance counters.
 * @returns {$CancellablePromise<metrics$0.Snapshot>}
 */
export function Metrics() {
    return $Call.ByID(3687510332).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SystemInfo returns platform information.
 * @returns {$CancellablePromise<system$0.Info>}
 */
export function SystemInfo() {
    return $Call.ByID(1223730458).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Version returns the application version string.
 * @returns {$CancellablePromise<string>}
 */
export function Version() {
    return $Call.ByID(2987005461);
}

// Private type creation functions
const $$createType0 = system$0.CoreBinary.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = metrics$0.Snapshot.createFrom;
const $$createType3 = system$0.Info.createFrom;
