// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DiscoveryService exposes the discovery engine, environment
 * intelligence and the adaptive start flow to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as discovery$0 from "../discovery/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netcheck$0 from "../netcheck/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelStartFlow cancels a running flow (user action).
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelStartFlow() {
    return $Call.ByID(1373871433);
}

/**
 * DiscoverNow runs one discovery pass at the requested depth and
 * persists the newly discovered candidates into the store. This is
 * the manual "Discover now" control.
 * @param {boolean} deep
 * @returns {$CancellablePromise<discovery$0.Stats | null>}
 */
export function DiscoverNow(deep) {
    return $Call.ByID(541104686, deep).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Environment returns the cached environment analysis, refreshing it
 * when older than the cache window (5 minutes).
 * @returns {$CancellablePromise<netcheck$0.Environment>}
 */
export function Environment() {
    return $Call.ByID(3946081290).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * PublicSourceDiscovery runs one bounded public-source discovery
 * cycle (v0.9.7 §7): the GitHub adapter plus the generic HTTP
 * connector feed the shared candidate queue; validated material lands
 * in the staging ledger with full provenance. Configured sources are
 * never displaced and discovered nodes are NOT auto-tested.
 * @returns {$CancellablePromise<discovery$0.GitHubOutcome | null>}
 */
export function PublicSourceDiscovery() {
    return $Call.ByID(2882109861).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * PublicSourceRateLimits returns the per-provider request accounting
 * (v0.9.7 §8): requests, successes, failures, 429/403 counters,
 * remaining budget and cooldown state.
 * @returns {$CancellablePromise<discovery$0.ProviderStats[]>}
 */
export function PublicSourceRateLimits() {
    return $Call.ByID(519656371).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * PublicSourceStaged returns the staged discovered sources (§9
 * provenance ledger view for the UI).
 * @returns {$CancellablePromise<$models.stagingEntry[]>}
 */
export function PublicSourceStaged() {
    return $Call.ByID(388491867).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * RunStartFlow executes the full adaptive flow:
 * DETECT → DISCOVER → TEST → RANK → CONNECT → VERIFY. Manual
 * selection override: a non-empty manualFingerprint connects exactly
 * that candidate, skipping automatic selection.
 * @param {string} manualFingerprint
 * @returns {$CancellablePromise<$models.StartFlowResult | null>}
 */
export function RunStartFlow(manualFingerprint) {
    return $Call.ByID(3620379966, manualFingerprint).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * SetFlowListener installs the event listener used by the runtime to
 * forward start-flow progress to the UI.
 * @param {any} fn
 * @returns {$CancellablePromise<void>}
 */
export function SetFlowListener(fn) {
    return $Call.ByID(945008607, fn);
}

/**
 * SourceHealthList returns the measured health of every known source
 * (the Source Intelligence surface, §16).
 * @returns {$CancellablePromise<discovery$0.SourceHealth[]>}
 */
export function SourceHealthList() {
    return $Call.ByID(3893868906).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * StartFlowStatus returns the current flow status.
 * @returns {$CancellablePromise<$models.StartFlowStatus>}
 */
export function StartFlowStatus() {
    return $Call.ByID(3056004253).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

// Private type creation functions
const $$createType0 = discovery$0.Stats.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = netcheck$0.Environment.createFrom;
const $$createType3 = discovery$0.GitHubOutcome.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = discovery$0.ProviderStats.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = $models.stagingEntry.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = $models.StartFlowResult.createFrom;
const $$createType10 = $Create.Nullable($$createType9);
const $$createType11 = discovery$0.SourceHealth.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.StartFlowStatus.createFrom;
