// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ImportService implements first-class personal configuration import.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * PreviewImport parses, validates and capability-resolves the payload
 * WITHOUT persisting anything. It is the read-only half of the import
 * flow; SaveImportedConfigs is the durable half.
 * @param {string} payload
 * @returns {$CancellablePromise<$models.ImportPreview>}
 */
export function PreviewImport(payload) {
    return $Call.ByID(3808533991, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SaveImportedConfigs re-parses the payload and persists every
 * parseable configuration through the ONE store path. Re-parsing (vs
 * caching preview state) keeps the service stateless: the saved truth
 * is always derived from the same bytes the user pasted.
 * @param {string} payload
 * @returns {$CancellablePromise<$models.ImportResult>}
 */
export function SaveImportedConfigs(payload) {
    return $Call.ByID(2208309854, payload).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ImportPreview.createFrom;
const $$createType1 = $models.ImportResult.createFrom;
