// @ts-check
// This file is automatically generated. DO NOT EDIT

/**
 * InternetToolsService exposes the shared Internet-Tools engine
 * (§6): user-triggered, bounded, structured diagnostics.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Tools lists the catalogue for the UI.
 * @returns {$CancellablePromise<any[]>}
 */
export function Tools() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.InternetToolsService.Tools");
}

/**
 * RunTool executes ONE tool on explicit user action.
 * @param {any} view
 * @returns {$CancellablePromise<any>}
 */
export function RunTool(view) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.InternetToolsService.RunTool", view);
}

/**
 * LiveTunnel renders the current tunnel truth for the UI.
 * @returns {$CancellablePromise<any>}
 */
export function LiveTunnel() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.InternetToolsService.LiveTunnel");
}

/**
 * NetworkIdentity runs the bounded Network Identity check (v0.9.8.5
 * §6): local IP (route-relevant, no traffic), public IP and
 * ISP/ASN metadata. Explicit user action only — never automatic.
 * @param {any} req
 * @returns {$CancellablePromise<any>}
 */
export function NetworkIdentity(req) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.InternetToolsService.NetworkIdentity", req);
}
