// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * InternetToolsService is the Wails-bound tools surface.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netcheck$0 from "../netcheck/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * LiveTunnel renders the current tunnel truth for the UI (the tools
 * panel header): measured, live, never fabricated.
 * @returns {$CancellablePromise<netcheck$0.TunnelSnapshot | null>}
 */
export function LiveTunnel() {
    return $Call.ByID(1907881339).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * NetworkIdentity runs the bounded Network Identity check (v0.9.8.5
 * §6): local IP (route-relevant, no traffic), public IP (the shared
 * identity endpoints) and ISP/ASN metadata (documented keyless
 * sources). It runs ONLY on this explicit call, honours the tool
 * concurrency bound, and returns the cached result for at most one
 * minute (UI convenience) before requiring a fresh explicit request.
 * @param {$models.NetworkIdentityRequest} req
 * @returns {$CancellablePromise<netcheck$0.IdentityReport | null>}
 */
export function NetworkIdentity(req) {
    return $Call.ByID(3979386589, req).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RunTool executes ONE tool on explicit user action.
 * @param {$models.ToolRequestView} view
 * @returns {$CancellablePromise<netcheck$0.ToolResult>}
 */
export function RunTool(view) {
    return $Call.ByID(221084438, view).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Tools lists the catalogue for the UI.
 * @returns {$CancellablePromise<netcheck$0.ToolInfo[]>}
 */
export function Tools() {
    return $Call.ByID(2471024802).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

// Private type creation functions
const $$createType0 = netcheck$0.TunnelSnapshot.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = netcheck$0.IdentityReport.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = netcheck$0.ToolResult.createFrom;
const $$createType5 = netcheck$0.ToolInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
