// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService exposes the persistent runtime log to the diagnostics UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logging$0 from "../../internal/logging/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Clear empties the in-memory diagnostics buffer. The on-disk log is
 * preserved: it is the durable diagnostic record.
 * @returns {$CancellablePromise<void>}
 */
export function Clear() {
    return $Call.ByID(1669906034);
}

/**
 * LogFile returns the primary runtime log file path for display.
 * @returns {$CancellablePromise<string>}
 */
export function LogFile() {
    return $Call.ByID(193626983);
}

/**
 * OpenLogsDir opens the platform file manager at the log directory.
 * @returns {$CancellablePromise<void>}
 */
export function OpenLogsDir() {
    return $Call.ByID(4206802217);
}

/**
 * Recent returns a bounded, incremental page of redacted entries.
 * @param {$models.LogFilter} filter
 * @returns {$CancellablePromise<$models.LogPage>}
 */
export function Recent(filter) {
    return $Call.ByID(3039547118, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Related returns every entry correlated with the given event id
 * (children via parent_event_id, batch/test/config siblings). Powers
 * the diagnostics "show related" action (v0.9.7 §20).
 * @param {string} eventID
 * @param {number} limit
 * @returns {$CancellablePromise<logging$0.Entry[]>}
 */
export function Related(eventID, limit) {
    return $Call.ByID(3065589544, eventID, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Subsystems lists the subsystems present in the current buffer
 * (filter dropdown values).
 * @returns {$CancellablePromise<string[]>}
 */
export function Subsystems() {
    return $Call.ByID(2856078077).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.LogPage.createFrom;
const $$createType1 = logging$0.Entry.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
