// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * LogService exposes the persistent runtime log to the diagnostics UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Recent returns a bounded, incremental page of redacted entries.
 * @param {$models.LogFilter} filter
 * @returns {$CancellablePromise<$models.LogPage>}
 */
export function Recent(filter) {
    return $Call.ByID(3039547118, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Subsystems lists the subsystems present in the current buffer
 * (filter dropdown values).
 * @returns {$CancellablePromise<Array<string>>}
 */
export function Subsystems() {
    return $Call.ByID(2856078077);
}

/**
 * Clear empties the in-memory diagnostics buffer. The on-disk log is
 * preserved: it is the durable diagnostic record.
 * @returns {$CancellablePromise<void>}
 */
export function Clear() {
    return $Call.ByID(1669906034);
}

/**
 * LogFile returns the primary runtime log file path for display.
 * @returns {$CancellablePromise<string>}
 */
export function LogFile() {
    return $Call.ByID(193626983);
}

/**
 * OpenLogsDir opens the platform file manager at the log directory.
 * @returns {$CancellablePromise<void>}
 */
export function OpenLogsDir() {
    return $Call.ByID(4206802217);
}

// Private type creation functions
const $$createType1 = $models.LogPage.createFrom;
