// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as config$0 from "../config/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../pipeline/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as logging$0 from "../../internal/logging/models.js";

/**
 * AppState is the application state surfaced to the UI.
 */
export class AppState {
    /**
     * Creates a new AppState instance.
     * @param {Partial<AppState>} [$$source = {}] - The source object to create the AppState.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("started_at" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["started_at"] = 0;
        }
        if (!("config_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["config_count"] = 0;
        }
        if (!("ingestion_running" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ingestion_running"] = false;
        }
        if (!("native_acceleration" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["native_acceleration"] = "";
        }
        if (!("storage" in $$source)) {
            /**
             * @member
             * @type {store$0.Stats}
             */
            this["storage"] = (new store$0.Stats());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {pipeline$0.Stats | null | undefined}
             */
            this["last_ingestion"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppState}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType0;
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("storage" in $$parsedSource) {
            $$parsedSource["storage"] = $$createField6_0($$parsedSource["storage"]);
        }
        if ("last_ingestion" in $$parsedSource) {
            $$parsedSource["last_ingestion"] = $$createField7_0($$parsedSource["last_ingestion"]);
        }
        return new AppState(/** @type {Partial<AppState>} */($$parsedSource));
    }
}

/**
 * CacheStats summarizes the cache layers.
 */
export class CacheStats {
    /**
     * Creates a new CacheStats instance.
     * @param {Partial<CacheStats>} [$$source = {}] - The source object to create the CacheStats.
     */
    constructor($$source = {}) {
        if (!("hot_config_entries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hot_config_entries"] = 0;
        }
        if (!("hot_config_hits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hot_config_hits"] = 0;
        }
        if (!("hot_config_misses" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hot_config_misses"] = 0;
        }
        if (!("hot_config_hit_rate" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["hot_config_hit_rate"] = 0;
        }
        if (!("source_entries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["source_entries"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CacheStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CacheStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CacheStats(/** @type {Partial<CacheStats>} */($$parsedSource));
    }
}

/**
 * ConfigPage is one page of configurations for virtualized lists.
 */
export class ConfigPage {
    /**
     * Creates a new ConfigPage instance.
     * @param {Partial<ConfigPage>} [$$source = {}] - The source object to create the ConfigPage.
     */
    constructor($$source = {}) {
        if (!("items" in $$source)) {
            /**
             * @member
             * @type {config$0.Config[]}
             */
            this["items"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }
        if (!("offset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["offset"] = 0;
        }
        if (!("has_more" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["has_more"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigPage}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("items" in $$parsedSource) {
            $$parsedSource["items"] = $$createField0_0($$parsedSource["items"]);
        }
        return new ConfigPage(/** @type {Partial<ConfigPage>} */($$parsedSource));
    }
}

/**
 * SourceView is the UI projection of a source.
 */
export class SourceView {
    /**
     * Creates a new SourceView instance.
     * @param {Partial<SourceView>} [$$source = {}] - The source object to create the SourceView.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_hash"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceView(/** @type {Partial<SourceView>} */($$parsedSource));
    }
}

/**
 * VerifyResult reports the outcome of a storage verification.
 */
export class VerifyResult {
    /**
     * Creates a new VerifyResult instance.
     * @param {Partial<VerifyResult>} [$$source = {}] - The source object to create the VerifyResult.
     */
    constructor($$source = {}) {
        if (!("chunks_checked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["chunks_checked"] = 0;
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VerifyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VerifyResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VerifyResult(/** @type {Partial<VerifyResult>} */($$parsedSource));
    }
}

/**
 * BackendView is the UI projection of one protocol-core backend.
 */
export class BackendView {
    /**
     * Creates a new BackendView instance.
     * @param {Partial<BackendView>} [$$source = {}] - The source object to create the BackendView.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (!("priority" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["priority"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["summary"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["notes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_check"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["note"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["pinned_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackendView instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BackendView}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackendView(/** @type {Partial<BackendView>} */($$parsedSource));
    }
}

/**
 * ConfigDetail is the configuration details view: credential fields
 * are redacted by default.
 */
export class ConfigDetail {
    /**
     * Creates a new ConfigDetail instance.
     * @param {Partial<ConfigDetail>} [$$source = {}] - The source object to create the ConfigDetail.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (!("address" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["address"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["network"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["host"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["service"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["security"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["server_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["method"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["username"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["has_password"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["has_uuid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["has_public_key"] = undefined;
        }
        if (!("working" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["working"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["tested_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["source"] = undefined;
        }
        if (!("display" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["display"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["compatible_backends"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigDetail}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConfigDetail(/** @type {Partial<ConfigDetail>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = store$0.Stats.createFrom;
const $$createType1 = pipeline$0.Stats.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = config$0.Config.createFrom;
const $$createType4 = $Create.Array($$createType3);

/**
 * Settings is the persisted user preference set.
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("preferred_backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["preferred_backend"] = "";
        }
        if (!("refresh_interval_minutes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["refresh_interval_minutes"] = 0;
        }
        if (!("testing_policy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["testing_policy"] = "";
        }
        if (!("log_level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["log_level"] = "";
        }
        if (!("log_max_bytes_mb" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["log_max_bytes_mb"] = 0;
        }
        if (!("log_max_backups" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["log_max_backups"] = 0;
        }
        if (!("reduced_motion" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reduced_motion"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * LogFilter selects which entries Recent returns.
 */
export class LogFilter {
    /**
     * Creates a new LogFilter instance.
     * @param {Partial<LogFilter>} [$$source = {}] - The source object to create the LogFilter.
     */
    constructor($$source = {}) {
        if (!("since_seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["since_seq"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("subsystem" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subsystem"] = "";
        }
        if (!("query" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["query"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogFilter instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogFilter}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LogFilter(/** @type {Partial<LogFilter>} */($$parsedSource));
    }
}

/**
 * LogPage is one bounded page of runtime log entries.
 */
export class LogPage {
    /**
     * Creates a new LogPage instance.
     * @param {Partial<LogPage>} [$$source = {}] - The source object to create the LogPage.
     */
    constructor($$source = {}) {
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {import("../../internal/logging/models.js").Entry[]}
             */
            this["entries"] = [];
        }
        if (!("last_seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["last_seq"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LogPage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LogPage}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        const result = new LogPage(/** @type {Partial<LogPage>} */($$parsedSource));
        if ($$parsedSource != null && $$parsedSource["entries"] != null) {
            result["entries"] = $$parsedSource["entries"].map($$castEntry);
        }
        return result;
    }
}

const $$create0 = logging$0.Entry.createFrom;

/**
 * Casts one raw entry object into an Entry instance.
 * @param {any} $$value
 * @returns {InstanceType<typeof logging$0.Entry>}
 */
function $$castEntry($$value) {
    return $$create0($$value);
}
