// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * NetworkService is bound to the Wails runtime.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as netcheck$0 from "../netcheck/models.js";

/**
 * CheckConnection runs the full probe set. The proxy address is taken
 * from the active connection session when one exists, so the report
 * can distinguish proxy-only and core-side failures. A bounded
 * context guarantees the call returns even with black-holed probes.
 * @returns {$CancellablePromise<netcheck$0.Report | null>}
 */
export function CheckConnection() {
    return $Call.ByID(1486173083).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * LastReport returns the most recent report without re-running probes
 * (nil when no check has run yet in this session).
 * @returns {$CancellablePromise<netcheck$0.Report | null>}
 */
export function LastReport() {
    return $Call.ByID(1897202067).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = netcheck$0.Report.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
