// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProfileService exposes connection profiles to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Active returns the currently active profile (ok=false when no
 * profile is active).
 * @returns {$CancellablePromise<[$models.ProfileView, boolean]>}
 */
export function Active() {
    return $Call.ByID(3623620328).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType0($result[0]);
        return $result;
    }));
}

/**
 * ClearDefault removes the startup-profile marker.
 * @returns {$CancellablePromise<void>}
 */
export function ClearDefault() {
    return $Call.ByID(356465640);
}

/**
 * Create adds a profile and persists it. Validation happens through
 * validateProfileSpec (same port/backend rules as the settings
 * service); no credential field exists on the payload.
 * @param {$models.ProfileSpec} spec
 * @returns {$CancellablePromise<$models.ProfileView>}
 */
export function Create(spec) {
    return $Call.ByID(4193463690, spec).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Delete removes one profile. Configurations are NEVER touched —
 * they live in the store and a profile only references them. If the
 * deleted profile was active or default, those markers are cleared
 * (the runtime preferences themselves are left as they are: they are
 * ordinary settings until another profile is applied).
 * @param {string} profileID
 * @returns {$CancellablePromise<void>}
 */
export function Delete(profileID) {
    return $Call.ByID(661004409, profileID);
}

/**
 * Duplicate copies one profile under a derived unique name. The copy
 * is never active; it inherits every preference field.
 * @param {string} profileID
 * @returns {$CancellablePromise<$models.ProfileView>}
 */
export function Duplicate(profileID) {
    return $Call.ByID(3651570559, profileID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * List returns every profile in deterministic order with live
 * Active/Default flags and the live configuration availability. A
 * configuration that no longer resolves is reported honestly
 * (ConfigAvailable=false) — never invented, never silently dropped
 * here: persisted pruning happens at boot (initProfiles) and after
 * configuration deletions (pruneMissingConfigReferences), while
 * activation REFUSES a dangling reference loudly.
 * @returns {$CancellablePromise<$models.ProfileView[]>}
 */
export function List() {
    return $Call.ByID(2818086650).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Rename renames one profile (edit of the name field only).
 * @param {string} profileID
 * @param {string} name
 * @returns {$CancellablePromise<$models.ProfileView>}
 */
export function Rename(profileID, name) {
    return $Call.ByID(1243308520, profileID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetActive selects the active profile and applies its preferences
 * through the ONE settings path (persistSettings → validateSettings →
 * applySettings → the live connection manager). The preferences take
 * effect on the next connect — which runs through the existing
 * Quick Connect / ConnectionService flows with their verification,
 * trust and recovery rules UNCHANGED. A profile never connects by
 * itself and can never bypass any safety boundary.
 * 
 * v0.9.11 coherence contract: the settings mutation and the
 * active-marker write happen under ONE profiles.mu critical section,
 * so two concurrent activations can never tear the state (the marker
 * of one profile with the preferences of another). The lock order
 * profiles.mu → a.mu is the same one applyDefaultProfileAtBoot uses,
 * and no path takes them in reverse.
 * @param {string} profileID
 * @returns {$CancellablePromise<$models.ProfileView>}
 */
export function SetActive(profileID) {
    return $Call.ByID(1942630144, profileID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * SetDefault marks one profile as the startup profile: it is applied
 * (in memory, through the one settings path) on every boot until the
 * marker is cleared or changed.
 * @param {string} profileID
 * @returns {$CancellablePromise<void>}
 */
export function SetDefault(profileID) {
    return $Call.ByID(2380140731, profileID);
}

/**
 * Update replaces the editable fields of one profile.
 * @param {string} profileID
 * @param {$models.ProfileSpec} spec
 * @returns {$CancellablePromise<$models.ProfileView>}
 */
export function Update(profileID, spec) {
    return $Call.ByID(3602135575, profileID, spec).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ProfileView.createFrom;
const $$createType1 = $Create.Array($$createType0);
