// @ts-check
// This file is automatically generated. DO NOT EDIT

/**
 * ProviderService exposes the unified provider lifecycle (§12/§13):
 * Xray / V2Ray / sing-box adapters plus the first-class Tor and
 * Psiphon engines.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

/**
 * Modes lists the provider choices with labels (§12).
 * @returns {$CancellablePromise<any[]>}
 */
export function Modes() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Modes");
}

/**
 * Mode returns the effective provider mode from settings.
 * @returns {$CancellablePromise<string>}
 */
export function Mode() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Mode");
}

/**
 * SetMode persists the provider mode choice.
 * @param {string} mode
 * @returns {$CancellablePromise<string>}
 */
export function SetMode(mode) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.SetMode", mode);
}

/**
 * List renders every provider's Info.
 * @returns {$CancellablePromise<any[]>}
 */
export function List() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.List");
}

/**
 * Info renders one provider.
 * @param {string} name
 * @returns {$CancellablePromise<any>}
 */
export function Info(name) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Info", name);
}

/**
 * Health measures one provider (bounded).
 * @param {string} name
 * @returns {$CancellablePromise<any>}
 */
export function Health(name) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Health", name);
}

/**
 * Install runs a provider's managed download pipeline.
 * @param {string} name
 * @returns {$CancellablePromise<any>}
 */
export function Install(name) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Install", name);
}

/**
 * Uninstall removes a provider's binaries and runtime data.
 * @param {string} name
 * @returns {$CancellablePromise<any>}
 */
export function Uninstall(name) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Uninstall", name);
}

/**
 * Start launches a provider's managed instance.
 * @param {string} name
 * @returns {$CancellablePromise<any>}
 */
export function Start(name) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Start", name);
}

/**
 * Stop shuts a provider's managed instance down.
 * @param {string} name
 * @returns {$CancellablePromise<any>}
 */
export function Stop(name) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Stop", name);
}

/**
 * SetTorOptions validates and applies bridge configuration.
 * @param {any} view
 * @returns {$CancellablePromise<void>}
 */
export function SetTorOptions(view) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.SetTorOptions", view);
}

/**
 * SetPsiphonExtraConfig validates and applies advanced config.
 * @param {string} extra
 * @returns {$CancellablePromise<void>}
 */
export function SetPsiphonExtraConfig(extra) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.SetPsiphonExtraConfig", extra);
}

/**
 * SetPsiphonUserBinary adopts a user-provided binary (validated).
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetPsiphonUserBinary(path) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.SetPsiphonUserBinary", path);
}

/**
 * AutoChoices returns the evidence-scored provider options.
 * @returns {$CancellablePromise<any[]>}
 */
export function AutoChoices() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.AutoChoices");
}

/**
 * Connect establishes a session through one provider.
 * @param {string} name
 * @returns {$CancellablePromise<any>}
 */
export function Connect(name) {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.Connect", name);
}

/**
 * ConnectAuto implements the Auto provider mode (§12).
 * @returns {$CancellablePromise<any>}
 */
export function ConnectAuto() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.ConnectAuto");
}

/**
 * CurrentProvider reports the active session's provider.
 * @returns {$CancellablePromise<string>}
 */
export function CurrentProvider() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.ProviderService.CurrentProvider");
}
