// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProviderService is the Wails-bound provider surface (§13).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "../connection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as provider$0 from "../provider/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AutoChoices returns the evidence-scored provider options and the
 * winner (§12). Explainable, like configuration ranking.
 * @returns {$CancellablePromise<[$models.ProviderChoice[], string]>}
 */
export function AutoChoices() {
    return $Call.ByID(2178458555).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType1($result[0]);
        return $result;
    }));
}

/**
 * Connect establishes a session through one provider — through the
 * EXISTING connection lifecycle (start → ready → verify → connected).
 * @param {string} name
 * @returns {$CancellablePromise<connection$0.Snapshot>}
 */
export function Connect(name) {
    return $Call.ByID(985583732, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * ConnectAuto implements the Auto provider mode (§12): evidence-based
 * selection, then the same connection lifecycle. Falls back to the
 * classic configuration flow when configurations win the evidence.
 * @returns {$CancellablePromise<[connection$0.Snapshot, string]>}
 */
export function ConnectAuto() {
    return $Call.ByID(1822064787).then(/** @type {($result: any) => any} */(($result) => {
        $result[0] = $$createType2($result[0]);
        return $result;
    }));
}

/**
 * CurrentProvider reports the active session's provider ("" for
 * configuration sessions).
 * @returns {$CancellablePromise<string>}
 */
export function CurrentProvider() {
    return $Call.ByID(759943630);
}

/**
 * Health measures one provider (bounded).
 * @param {string} name
 * @returns {$CancellablePromise<provider$0.Health>}
 */
export function Health(name) {
    return $Call.ByID(3334763188, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * Info renders one provider.
 * @param {string} name
 * @returns {$CancellablePromise<provider$0.Info>}
 */
export function Info(name) {
    return $Call.ByID(2189494998, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Install runs a provider's managed download pipeline (long-running;
 * progress through structured logs).
 * @param {string} name
 * @returns {$CancellablePromise<provider$0.Info>}
 */
export function Install(name) {
    return $Call.ByID(2481182973, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * List renders every provider's Info (§13: installed, version,
 * healthy, runtime state, source, license/notice, last check).
 * @returns {$CancellablePromise<provider$0.Info[]>}
 */
export function List() {
    return $Call.ByID(3591794226).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Mode returns the effective provider mode from settings.
 * @returns {$CancellablePromise<string>}
 */
export function Mode() {
    return $Call.ByID(3756008045);
}

/**
 * Modes lists the provider choices with labels (§12).
 * @returns {$CancellablePromise<$models.ProviderModeView[]>}
 */
export function Modes() {
    return $Call.ByID(2346038586).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * SetMode persists the provider mode choice.
 * @param {string} mode
 * @returns {$CancellablePromise<string>}
 */
export function SetMode(mode) {
    return $Call.ByID(2204579013, mode);
}

/**
 * SetPsiphonExtraConfig validates and applies advanced Psiphon
 * config.
 * @param {string} extra
 * @returns {$CancellablePromise<void>}
 */
export function SetPsiphonExtraConfig(extra) {
    return $Call.ByID(1790003033, extra);
}

/**
 * SetPsiphonUserBinary adopts a user-provided binary (validated).
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function SetPsiphonUserBinary(path) {
    return $Call.ByID(866290465, path);
}

/**
 * SetTorOptions validates and applies bridge configuration (§8: no
 * hardcoded bridges; user-provided only, validated before launch).
 * @param {$models.TorOptionsView} view
 * @returns {$CancellablePromise<void>}
 */
export function SetTorOptions(view) {
    return $Call.ByID(1518258327, view);
}

/**
 * Start launches a provider's managed instance WITHOUT establishing
 * a connection session (advanced; Quick Connect uses Connect).
 * @param {string} name
 * @returns {$CancellablePromise<provider$0.Info>}
 */
export function Start(name) {
    return $Call.ByID(3171181862, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Stop shuts a provider's managed instance down.
 * @param {string} name
 * @returns {$CancellablePromise<provider$0.Info>}
 */
export function Stop(name) {
    return $Call.ByID(802293006, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * Uninstall removes a provider's binaries and runtime data.
 * @param {string} name
 * @returns {$CancellablePromise<provider$0.Info>}
 */
export function Uninstall(name) {
    return $Call.ByID(2537544736, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.ProviderChoice.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = connection$0.Snapshot.createFrom;
const $$createType3 = provider$0.Health.createFrom;
const $$createType4 = provider$0.Info.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = $models.ProviderModeView.createFrom;
const $$createType7 = $Create.Array($$createType6);
