// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ProxyChainService exposes proxy chains to the UI over the SAME
 * collections authority used by favorites and user groups.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddHop inserts a configuration into the chain at position
 * (0-based; position < 0 or >= hops appends).
 * @param {string} chainID
 * @param {string} configID
 * @param {number} position
 * @returns {$CancellablePromise<void>}
 */
export function AddHop(chainID, configID, position) {
    return $Call.ByID(2663870460, chainID, configID, position);
}

/**
 * CheckChain runs the honest chain check: every hop's REAL stored
 * evidence plus a FRESH end-to-end measurement through the compiled
 * chain (one core process, bounded, instance closed afterwards).
 * Per-hop readiness alone is never success.
 * @param {string} chainID
 * @returns {$CancellablePromise<$models.ChainCheckResult | null>}
 */
export function CheckChain(chainID) {
    return $Call.ByID(3494282847, chainID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CreateProxyChain builds a chain from an ordered list of existing
 * configuration IDs and persists it atomically.
 * @param {string} name
 * @param {string[]} configIDs
 * @returns {$CancellablePromise<$models.ProxyChainView>}
 */
export function CreateProxyChain(name, configIDs) {
    return $Call.ByID(2439653615, name, configIDs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DeleteProxyChain removes one chain (configurations are untouched —
 * they live in the store, not the chain).
 * @param {string} chainID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteProxyChain(chainID) {
    return $Call.ByID(2702605560, chainID);
}

/**
 * ListProxyChains returns every chain with hop counts.
 * @returns {$CancellablePromise<$models.ProxyChainView[]>}
 */
export function ListProxyChains() {
    return $Call.ByID(3831005676).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * ProxyChainDetails renders the full editor/connect projection.
 * @param {string} chainID
 * @returns {$CancellablePromise<$models.ProxyChainDetails | null>}
 */
export function ProxyChainDetails(chainID) {
    return $Call.ByID(4110604939, chainID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * RemoveHop removes one configuration from the chain (a chain falling
 * below two hops refuses — one hop is a plain connection, not a
 * chain).
 * @param {string} chainID
 * @param {string} configID
 * @returns {$CancellablePromise<void>}
 */
export function RemoveHop(chainID, configID) {
    return $Call.ByID(1319698589, chainID, configID);
}

/**
 * RenameProxyChain renames one chain.
 * @param {string} chainID
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function RenameProxyChain(chainID, name) {
    return $Call.ByID(282693285, chainID, name);
}

/**
 * ReorderHop moves one hop to a new 0-based position (clamped).
 * @param {string} chainID
 * @param {string} configID
 * @param {number} position
 * @returns {$CancellablePromise<void>}
 */
export function ReorderHop(chainID, configID, position) {
    return $Call.ByID(2525665844, chainID, configID, position);
}

/**
 * ValidateProxyChain validates a candidate hop list (editor preview
 * before save). The list need not be persisted.
 * @param {string[]} configIDs
 * @returns {$CancellablePromise<void>}
 */
export function ValidateProxyChain(configIDs) {
    return $Call.ByID(1530269141, configIDs);
}

// Private type creation functions
const $$createType0 = $models.ChainCheckResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.ProxyChainView.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = $models.ProxyChainDetails.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
