// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SettingsService exposes user preferences to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Get returns the active settings.
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function Get() {
    return $Call.ByID(1786991218).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Save validates, persists and applies new settings. The saved value
 * is returned so the UI can reconcile.
 * @param {$models.Settings} settings
 * @returns {$CancellablePromise<$models.Settings>}
 */
export function Save(settings) {
    return $Call.ByID(860189907, settings).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Settings.createFrom;
