// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SourceService manages configuration sources.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as pipeline$0 from "../pipeline/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as source$0 from "../source/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Add registers a new source.
 * @param {string} id
 * @param {string} name
 * @param {string} url
 * @returns {$CancellablePromise<void>}
 */
export function Add(id, name, url) {
    return $Call.ByID(2645986349, id, name, url);
}

/**
 * List returns all configured sources.
 * @returns {$CancellablePromise<$models.SourceView[]>}
 */
export function List() {
    return $Call.ByID(1649179546).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * RefreshNow triggers an immediate ingestion cycle and waits for it
 * to finish. The UI should call this from a background task and show
 * progress via State.
 * @returns {$CancellablePromise<pipeline$0.Stats | null>}
 */
export function RefreshNow() {
    return $Call.ByID(1520272775).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * RefreshSource refreshes EXACTLY ONE source (v0.12.1 §18) through
 * the SAME ingestion architecture — the ONE fetcher, ONE parser
 * pipeline, ONE store, ONE scheduler. No second downloader, collector
 * or scheduler is created: the targeted operation snapshots the
 * single source and hands a one-element slice to the same Pipeline
 * instance the full cycles use.
 * 
 * Concurrency contract (single-owner gate): the targeted refresh and
 * a full ingestion cycle share the same ingesting flag. While a full
 * cycle is in flight the targeted refresh waits (bounded), then takes
 * the gate; while the targeted refresh holds the gate, a concurrent
 * full cycle is skipped by its existing skip-if-busy CAS. Two
 * ingestion authorities can never race.
 * 
 * The operation validates the source ID, respects the enabled policy
 * (a disabled source refuses an explicit refresh), preserves the
 * dedupe/content-hash behaviour (seenHashes), publishes the normal
 * source-refresh state and returns the source's own bounded stats.
 * @param {string} id
 * @returns {$CancellablePromise<source$0.Stats | null>}
 */
export function RefreshSource(id) {
    return $Call.ByID(2155144200, id).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Remove deletes a source.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function Remove(id) {
    return $Call.ByID(2224893482, id);
}

/**
 * SetEnabled enables or disables a source; the change persists
 * immediately.
 * @param {string} id
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetEnabled(id, enabled) {
    return $Call.ByID(3720130627, id, enabled);
}

/**
 * SourceReliability renders the evidence-based source health report
 * (cached; recomputed at most once per reliabilityCacheTTL or after
 * an evidence change).
 * @returns {$CancellablePromise<$models.SourceReliabilityReport | null>}
 */
export function SourceReliability() {
    return $Call.ByID(1732292637).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * SourceStatsList returns the statistics view of all sources.
 * @returns {$CancellablePromise<$models.SourceStatsView[]>}
 */
export function SourceStatsList() {
    return $Call.ByID(3558031882).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * UpdateSourceMetadata lets the user edit a source's metadata
 * (display name, priority, region, protocol hints, refresh interval).
 * @param {string} id
 * @param {$models.SourceMetadataUpdate} metadata
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSourceMetadata(id, metadata) {
    return $Call.ByID(1746651191, id, metadata);
}

// Private type creation functions
const $$createType0 = $models.SourceView.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = pipeline$0.Stats.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = source$0.Stats.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = $models.SourceReliabilityReport.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $Create.Array($$createType4);
