// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * StorageService exposes storage maintenance operations.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "../store/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Compact reclaims dead records.
 * @returns {$CancellablePromise<void>}
 */
export function Compact() {
    return $Call.ByID(4144358655);
}

/**
 * MigrateLegacy imports a legacy JSON database file into the store.
 * @param {string} path
 * @returns {$CancellablePromise<store$0.MigrationResult>}
 */
export function MigrateLegacy(path) {
    return $Call.ByID(1433223692, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * Stats returns the chunked-store statistics.
 * @returns {$CancellablePromise<store$0.Stats>}
 */
export function Stats() {
    return $Call.ByID(3282658569).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * Verify runs a full chunk integrity check. Progress can be observed
 * through the returned result.
 * @returns {$CancellablePromise<$models.VerifyResult>}
 */
export function Verify() {
    return $Call.ByID(2736124579).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * DataDir returns the resolved data directory. (v0.9.1 addition:
 * ByName path until the wails3 generator is rerun on a GUI toolchain
 * host — mirrors the Memory/BuildDiagnosticReport additions.)
 * @returns {$CancellablePromise<string>}
 */
export function DataDir() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.StorageService.DataDir");
}

/**
 * OpenDataDir opens the platform file manager at the data directory.
 * (v0.9.1 addition — ByName path, see DataDir.)
 * @returns {$CancellablePromise<void>}
 */
export function OpenDataDir() {
    return $Call.ByName("github.com/Parsaetak/FreeIran/engine/app.StorageService.OpenDataDir");
}

// Private type creation functions
const $$createType0 = store$0.MigrationResult.createFrom;
const $$createType1 = store$0.Stats.createFrom;
const $$createType2 = $models.VerifyResult.createFrom;
