// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TestQueueService exposes the test queue to the UI.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as testqueue$0 from "../testqueue/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Cancel cancels one queued task.
 * @param {number} taskID
 * @returns {$CancellablePromise<void>}
 */
export function Cancel(taskID) {
    return $Call.ByID(3163357610, taskID);
}

/**
 * CancelAll cancels every queued task.
 * @returns {$CancellablePromise<number>}
 */
export function CancelAll() {
    return $Call.ByID(603516689);
}

/**
 * CancelBySource cancels every queued task from one source.
 * @param {string} sourceID
 * @returns {$CancellablePromise<number>}
 */
export function CancelBySource(sourceID) {
    return $Call.ByID(1724974214, sourceID);
}

/**
 * Drain blocks until the queue is empty or 30 minutes elapse.
 * @returns {$CancellablePromise<void>}
 */
export function Drain() {
    return $Call.ByID(2935680306);
}

/**
 * Enqueue adds one configuration to the test queue.
 * @param {string} fingerprint
 * @param {string} protocol
 * @param {string[]} backends
 * @param {number} priority
 * @param {string} sourceID
 * @returns {$CancellablePromise<number>}
 */
export function Enqueue(fingerprint, protocol, backends, priority, sourceID) {
    return $Call.ByID(2006092850, fingerprint, protocol, backends, priority, sourceID);
}

/**
 * EnqueueByFilter scans the store and enqueues every matching
 * configuration. Bounded, streaming, and safe for tens of thousands
 * of records (the queue's duplicate suppression collapses repeats).
 * @param {$models.TestFilter} filter
 * @returns {$CancellablePromise<$models.TestBatchResult>}
 */
export function EnqueueByFilter(filter) {
    return $Call.ByID(4022949333, filter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * EnqueueMany adds many fingerprints at once. Returns the number of
 * tasks actually enqueued (duplicates are skipped).
 * @param {$models.EnqueueItem[]} tasks
 * @returns {$CancellablePromise<number>}
 */
export function EnqueueMany(tasks) {
    return $Call.ByID(2916723525, tasks);
}

/**
 * Pause suspends task pickup: queued tests stay pending while
 * in-flight tests finish (v0.9.7 bulk-testing UX).
 * @returns {$CancellablePromise<void>}
 */
export function Pause() {
    return $Call.ByID(64728162);
}

/**
 * Paused reports whether the queue is paused.
 * @returns {$CancellablePromise<boolean>}
 */
export function Paused() {
    return $Call.ByID(416271730);
}

/**
 * Resume lifts a Pause.
 * @returns {$CancellablePromise<void>}
 */
export function Resume() {
    return $Call.ByID(2816918883);
}

/**
 * SetMode changes the queue's testing mode preset. initMu serializes
 * the stop+recreate so a concurrent ensureQueue can't observe a
 * half-replaced queue or start a second new queue on top.
 * @param {testqueue$0.Mode} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetMode(mode) {
    return $Call.ByID(1960891763, mode);
}

/**
 * Snapshot returns the current pending + in-flight tasks (up to limit).
 * @param {number} limit
 * @returns {$CancellablePromise<testqueue$0.TaskSnapshot[]>}
 */
export function Snapshot(limit) {
    return $Call.ByID(759716196, limit).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * Stats returns the current queue statistics.
 * @returns {$CancellablePromise<testqueue$0.Stats>}
 */
export function Stats() {
    return $Call.ByID(2729506915).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.TestBatchResult.createFrom;
const $$createType1 = testqueue$0.TaskSnapshot.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = testqueue$0.Stats.createFrom;
