// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * TunnelService exposes the system-proxy / TUN tunnel modes.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as tunnel$0 from "../tunnel/models.js";

/**
 * Disable deactivates the active tunnel mode and restores previous settings.
 * @returns {$CancellablePromise<void>}
 */
export function Disable() {
    return $Call.ByID(158798555);
}

/**
 * EnableSystemProxy sets the Windows system proxy.
 * @param {string} host
 * @param {number} port
 * @param {boolean} asHTTP
 * @param {string[]} bypass
 * @returns {$CancellablePromise<void>}
 */
export function EnableSystemProxy(host, port, asHTTP, bypass) {
    return $Call.ByID(3358943137, host, port, asHTTP, bypass);
}

/**
 * EnableTUN reports the v0.9.8.6 TUN status: experimental and
 * disabled. The method is kept on the service surface so older
 * frontends receive the explicit, user-visible error instead of a
 * missing-method failure — the controller refuses TUN on every
 * platform (tunnel.ErrTunExperimental; see engine/tunnel/
 * tun_unavailable.go for why the Wintun backend was removed).
 * @param {string} host
 * @param {number} port
 * @returns {$CancellablePromise<void>}
 */
export function EnableTUN(host, port) {
    return $Call.ByID(3422265061, host, port);
}

/**
 * OwnershipStatus exposes the durable system-proxy ownership marker
 * (v0.10.2 § Windows system-proxy UX): whether FreeIran owns the
 * system proxy, the ownership phase, the recorded endpoint and the
 * saved previous state — the facts a recovery will apply, readable
 * without touching the platform proxy.
 * @returns {$CancellablePromise<tunnel$0.OwnershipStatus>}
 */
export function OwnershipStatus() {
    return $Call.ByID(3429419992).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * State returns the current tunnel state.
 * @returns {$CancellablePromise<tunnel$0.State>}
 */
export function State() {
    return $Call.ByID(3419848110).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = tunnel$0.OwnershipStatus.createFrom;
const $$createType1 = tunnel$0.State.createFrom;
