// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Attempt records one backend attempt for observability (§41).
 */
export class Attempt {
    /**
     * Creates a new Attempt instance.
     * @param {Partial<Attempt>} [$$source = {}] - The source object to create the Attempt.
     */
    constructor($$source = {}) {
        if (!("backend" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["backend"] = "";
        }
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Attempt instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Attempt}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Attempt(/** @type {Partial<Attempt>} */($$parsedSource));
    }
}

/**
 * Snapshot is the immutable state view surfaced to the UI (§16):
 * connection state, backend identity, configuration identity,
 * latency and the attempt history — all credential-free.
 * 
 * v0.9.7 metric semantics: CoreReadyMS is the LOCAL core startup→ready
 * duration; PingMedianMS / URLTotalMS come from an actual tunnel
 * verification (end-to-end). A ready listener is NOT Internet
 * connectivity — the two value families never substitute for each
 * other. LatencyMS mirrors the best known end-to-end measurement and
 * is empty until a verification (or tunnel probe) produced one.
 */
export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["core"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["core_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["config_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["config_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["config_display"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["started_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_error"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Attempt[] | undefined}
             */
            this["attempts"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["fallbacks_used"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * CorePID is the operating-system process id of the active core
             * (0 while no core session runs). It exists so lifecycle tests and
             * diagnostics can PROVE process teardown after a session ends
             * (v0.9.8.6): observing state=disconnected/connection_failed must
             * mean the supervised process is gone, not merely unmanaged.
             * @member
             * @type {number | undefined}
             */
            this["core_pid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.9.7 separated measurements.
             * @member
             * @type {number | undefined}
             */
            this["core_ready_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["ping_median_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["url_total_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * none|usable|failed|degraded
             * @member
             * @type {string | undefined}
             */
            this["verification"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.9.8.5 stability evidence (§2.3): when the session was last
             * verified usable, and how many consecutive stability rechecks
             * have failed since (0 while healthy).
             * @member
             * @type {number | undefined}
             */
            this["verified_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["verify_failures"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        const $$createField10_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("attempts" in $$parsedSource) {
            $$parsedSource["attempts"] = $$createField10_0($$parsedSource["attempts"]);
        }
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

/**
 * State is the explicit connection lifecycle state.
 * @readonly
 * @enum {string}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * StateDisconnected: no session.
     */
    StateDisconnected: "disconnected",

    /**
     * StateSelecting: resolving a backend for the configuration.
     */
    StateSelecting: "selecting",

    /**
     * StatePreparing: validating and generating the runtime config.
     */
    StatePreparing: "preparing",

    /**
     * StateStartingCore: spawning the protocol-core process.
     */
    StateStartingCore: "starting_core",

    /**
     * StateWaitingForReady: polling the local listener.
     */
    StateWaitingForReady: "waiting_for_ready",

    /**
     * StateConnected: the local route is established — the core
     * process runs and its proxy listener accepts connections. This is
     * readiness evidence, not Internet connectivity (v0.9.8.3).
     */
    StateConnected: "connected",

    /**
     * StateVerifying: an end-to-end Internet verification is running
     * through the established route (v0.9.8.3).
     */
    StateVerifying: "verifying",

    /**
     * StateConnectedVerified: the route carried real traffic to the
     * verification target — usable Internet connectivity (v0.9.8.3).
     */
    StateConnectedVerified: "connected_verified",

    /**
     * StateDisconnecting: stopping the core and cleaning up.
     */
    StateDisconnecting: "disconnecting",

    /**
     * StateConnectionFailed: the last attempt failed; no session.
     */
    StateConnectionFailed: "connection_failed",
};

// Private type creation functions
const $$createType0 = Attempt.createFrom;
const $$createType1 = $Create.Array($$createType0);
