// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Snapshot is a point-in-time view of all memory consumers. It is
 * safe to copy and surface to the UI.
 */
export class Snapshot {
    /**
     * Creates a new Snapshot instance.
     * @param {Partial<Snapshot>} [$$source = {}] - The source object to create the Snapshot.
     */
    constructor($$source = {}) {
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {State}
             */
            this["state"] = State.$zero;
        }
        if (!("heap_alloc" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["heap_alloc"] = 0;
        }
        if (!("heap_in_use" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["heap_in_use"] = 0;
        }
        if (!("rss" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rss"] = 0;
        }
        if (!("gc_cpu_fraction" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["gc_cpu_fraction"] = 0;
        }
        if (!("arena_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["arena_bytes"] = 0;
        }
        if (!("cache_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cache_bytes"] = 0;
        }
        if (!("queue_bytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["queue_bytes"] = 0;
        }
        if (!("pending_write" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pending_write"] = 0;
        }
        if (!("source_buffers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["source_buffers"] = 0;
        }
        if (!("parser_buffers" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["parser_buffers"] = 0;
        }
        if (!("usage_fraction" in $$source)) {
            /**
             * 0..1, weighted
             * @member
             * @type {number}
             */
            this["usage_fraction"] = 0;
        }
        if (!("sampled_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sampled_at"] = "0001-01-01T00:00:00.000Z";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Snapshot(/** @type {Partial<Snapshot>} */($$parsedSource));
    }
}

/**
 * State is the memory pressure level.
 * @readonly
 * @enum {number}
 */
export const State = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * StateNormal: memory is comfortable. Subsystems run at full capacity.
     */
    StateNormal: 0,

    /**
     * StateElevated: memory is moderately used. Subsystems should
     * reduce concurrency slightly and avoid warming unnecessary data.
     */
    StateElevated: 1,

    /**
     * StateHigh: memory is scarce. Subsystems should aggressively
     * reduce concurrency, flush selected caches, and accelerate
     * chunk flushes.
     */
    StateHigh: 2,

    /**
     * StateCritical: memory is exhausted. Subsystems should shed all
     * non-essential memory, release native free lists, and invoke GC.
     */
    StateCritical: 3,
};
