// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * GitHubOutcome is the per-run result summary of the GitHub adapter.
 */
export class GitHubOutcome {
    /**
     * Creates a new GitHubOutcome instance.
     * @param {Partial<GitHubOutcome>} [$$source = {}] - The source object to create the GitHubOutcome.
     */
    constructor($$source = {}) {
        if (!("repos_inspected" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["repos_inspected"] = 0;
        }
        if (!("trees_inspected" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["trees_inspected"] = 0;
        }
        if (!("probes_fetched" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["probes_fetched"] = 0;
        }
        if (!("candidates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["candidates"] = 0;
        }
        if (!("code_hits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["code_hits"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["strategy_notes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ProviderStats[] | undefined}
             */
            this["provider_stats"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GitHubOutcome instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GitHubOutcome}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("strategy_notes" in $$parsedSource) {
            $$parsedSource["strategy_notes"] = $$createField5_0($$parsedSource["strategy_notes"]);
        }
        if ("provider_stats" in $$parsedSource) {
            $$parsedSource["provider_stats"] = $$createField6_0($$parsedSource["provider_stats"]);
        }
        return new GitHubOutcome(/** @type {Partial<GitHubOutcome>} */($$parsedSource));
    }
}

/**
 * Level identifies one discovery level.
 * @readonly
 * @enum {number}
 */
export const Level = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    /**
     * LevelCached: the store's known node pool (cheapest; no network).
     */
    LevelCached: 1,

    /**
     * LevelConfigured: the user's configured sources.
     */
    LevelConfigured: 2,

    /**
     * LevelTrustedPublic: the built-in trusted public registry.
     */
    LevelTrustedPublic: 3,

    /**
     * LevelSearch: fresh public-source discovery via smart search.
     */
    LevelSearch: 4,

    /**
     * LevelContent: sources discovered from references inside valid
     * fetched content.
     */
    LevelContent: 5,

    /**
     * LevelRecovery: emergency re-discovery after connection
     * failures exhausted the known pool.
     */
    LevelRecovery: 6,

    /**
     * LevelDeep: restrictive-network escalation — search with more
     * queries and accept lower-yield sources.
     */
    LevelDeep: 7,
};

/**
 * LevelStats records what one level contributed.
 */
export class LevelStats {
    /**
     * Creates a new LevelStats instance.
     * @param {Partial<LevelStats>} [$$source = {}] - The source object to create the LevelStats.
     */
    constructor($$source = {}) {
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {Level}
             */
            this["level"] = Level.$zero;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("sources" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sources"] = 0;
        }
        if (!("fetched_ok" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fetched_ok"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("candidates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["candidates"] = 0;
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["valid"] = 0;
        }
        if (!("duplicates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicates"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["skipped"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["skip_reason"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LevelStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LevelStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LevelStats(/** @type {Partial<LevelStats>} */($$parsedSource));
    }
}

/**
 * Provenance is the full identity + quality ledger of one candidate
 * source (§9). Persisted next to the discovery health so restarts
 * keep trusting (and distrusting) the right material.
 */
export class Provenance {
    /**
     * Creates a new Provenance instance.
     * @param {Partial<Provenance>} [$$source = {}] - The source object to create the Provenance.
     */
    constructor($$source = {}) {
        if (!("source_id" in $$source)) {
            /**
             * Identity.
             * @member
             * @type {string}
             */
            this["source_id"] = "";
        }
        if (!("source_type" in $$source)) {
            /**
             * @member
             * @type {SourceType}
             */
            this["source_type"] = SourceType.$zero;
        }
        if (!("source_url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["source_url"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * GitHub origin (empty for plain HTTP sources).
             * @member
             * @type {string | undefined}
             */
            this["origin_repository"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["origin_path"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Causal chain: the source that referenced this one (empty for
             * seeded/configured roots).
             * @member
             * @type {string | undefined}
             */
            this["discovered_from"] = undefined;
        }
        if (!("first_seen" in $$source)) {
            /**
             * Lifecycle timestamps (UTC RFC3339 when rendered).
             * @member
             * @type {string}
             */
            this["first_seen"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("last_seen" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["last_seen"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_success"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_failure"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Last-fetch observations.
             * @member
             * @type {number | undefined}
             */
            this["http_status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["content_hash"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["content_size"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["fetch_latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["parser"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["etag"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_modified"] = undefined;
        }
        if (!("candidate_count" in $$source)) {
            /**
             * Yield ledger.
             * @member
             * @type {number}
             */
            this["candidate_count"] = 0;
        }
        if (!("valid_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["valid_count"] = 0;
        }
        if (!("duplicate_count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicate_count"] = 0;
        }
        if (!("depth" in $$source)) {
            /**
             * Recursion bookkeeping.
             * @member
             * @type {number}
             */
            this["depth"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Provenance instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Provenance}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Provenance(/** @type {Partial<Provenance>} */($$parsedSource));
    }
}

/**
 * ProviderStats is the per-provider accounting snapshot surfaced to
 * the UI and the structured log.
 */
export class ProviderStats {
    /**
     * Creates a new ProviderStats instance.
     * @param {Partial<ProviderStats>} [$$source = {}] - The source object to create the ProviderStats.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("requests" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["requests"] = 0;
        }
        if (!("successes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["successes"] = 0;
        }
        if (!("failures" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failures"] = 0;
        }
        if (!("rate_limited_429" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rate_limited_429"] = 0;
        }
        if (!("forbidden_403" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["forbidden_403"] = 0;
        }
        if (!("remaining" in $$source)) {
            /**
             * last reported X-RateLimit-Remaining
             * @member
             * @type {number}
             */
            this["remaining"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * last reported reset (RFC3339)
             * @member
             * @type {string | undefined}
             */
            this["reset_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["last_request_at"] = undefined;
        }
        if (!("avg_latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["avg_latency_ms"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["cooldown_until"] = undefined;
        }
        if (!("cooling_down" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cooling_down"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProviderStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProviderStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProviderStats(/** @type {Partial<ProviderStats>} */($$parsedSource));
    }
}

/**
 * SourceHealth is the observable health of one source.
 */
export class SourceHealth {
    /**
     * Creates a new SourceHealth instance.
     * @param {Partial<SourceHealth>} [$$source = {}] - The source object to create the SourceHealth.
     */
    constructor($$source = {}) {
        if (!("source_id" in $$source)) {
            /**
             * SourceID is the stable source identifier.
             * @member
             * @type {string}
             */
            this["source_id"] = "";
        }
        if (!("fetches" in $$source)) {
            /**
             * Fetches counts every observed fetch attempt.
             * @member
             * @type {number}
             */
            this["fetches"] = 0;
        }
        if (!("fetch_ok" in $$source)) {
            /**
             * FetchOK counts fetches that connected and returned a body.
             * @member
             * @type {number}
             */
            this["fetch_ok"] = 0;
        }
        if (!("parse_ok" in $$source)) {
            /**
             * ParseOK counts bodies that parsed without error.
             * @member
             * @type {number}
             */
            this["parse_ok"] = 0;
        }
        if (!("candidates" in $$source)) {
            /**
             * Candidates counts parsed candidates (pre-validation).
             * @member
             * @type {number}
             */
            this["candidates"] = 0;
        }
        if (!("valid" in $$source)) {
            /**
             * Valid counts candidates that normalized AND validated.
             * @member
             * @type {number}
             */
            this["valid"] = 0;
        }
        if (!("duplicates" in $$source)) {
            /**
             * Duplicates counts candidates identical to already-known ones.
             * @member
             * @type {number}
             */
            this["duplicates"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastLatencyMS is the measured fetch duration of the last
             * SUCCESS (0 = never succeeded).
             * @member
             * @type {number | undefined}
             */
            this["last_latency_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastSuccessAt/LastFailureAt are Unix milliseconds (0 = never).
             * @member
             * @type {number | undefined}
             */
            this["last_success_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["last_failure_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ConsecutiveFailures drives the backoff.
             * @member
             * @type {number | undefined}
             */
            this["consecutive_failures"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * LastError is the classified last failure (credential free).
             * @member
             * @type {string | undefined}
             */
            this["last_error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SourceHealth instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SourceHealth}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SourceHealth(/** @type {Partial<SourceHealth>} */($$parsedSource));
    }
}

/**
 * SourceType classifies where a candidate URL came from.
 * @readonly
 * @enum {string}
 */
export const SourceType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Source types.
     *
     * user-defined, never displaced
     */
    SourceTypeConfigured: "configured",

    /**
     * built-in list
     */
    SourceTypeDefault: "default",

    /**
     * autonomous discovery
     */
    SourceTypeDiscovered: "discovered",

    /**
     * linked from another source
     */
    SourceTypeReferenced: "referenced",
    SourceTypeGitHubRepo: "github-repo",
    SourceTypeGitHubCode: "github-code",
    SourceTypeGitHubTree: "github-tree",
    SourceTypeGitHubRel: "github-release",
    SourceTypeGist: "github-gist",
    SourceTypeContent: "content-ref",
};

/**
 * Stats summarizes one discovery run.
 */
export class Stats {
    /**
     * Creates a new Stats instance.
     * @param {Partial<Stats>} [$$source = {}] - The source object to create the Stats.
     */
    constructor($$source = {}) {
        if (!("levels" in $$source)) {
            /**
             * @member
             * @type {LevelStats[]}
             */
            this["levels"] = [];
        }
        if (!("discovered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discovered"] = 0;
        }
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["valid"] = 0;
        }
        if (!("duplicates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicates"] = 0;
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Stats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Stats}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("levels" in $$parsedSource) {
            $$parsedSource["levels"] = $$createField0_0($$parsedSource["levels"]);
        }
        return new Stats(/** @type {Partial<Stats>} */($$parsedSource));
    }
}

/**
 * Trust is the coarse trust band of a candidate source. Trust is
 * EARNED by validation and testing outcomes; it is never claimed.
 * @readonly
 * @enum {string}
 */
export const Trust = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Trust bands.
     *
     * not yet fetched/validated
     */
    TrustUnknown: "unknown",

    /**
     * fetched, candidates parsed
     */
    TrustDiscovered: "discovered",

    /**
     * produced ≥1 valid configuration
     */
    TrustValidated: "validated",

    /**
     * candidates passed connectivity tests
     */
    TrustTested: "tested",

    /**
     * recently produced usable nodes
     */
    TrustWorking: "working",

    /**
     * no successful refresh within TTL
     */
    TrustStale: "stale",

    /**
     * persistently failing fetch/parse
     */
    TrustFailed: "failed",
};

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ProviderStats.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = LevelStats.createFrom;
const $$createType4 = $Create.Array($$createType3);
