// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry is one structured runtime log record (§17 + v0.9.7 session
 * identity and correlation fields).
 */
export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }
        if (!("ts" in $$source)) {
            /**
             * RFC3339, UTC
             * @member
             * @type {string}
             */
            this["ts"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {Level}
             */
            this["level"] = Level.$zero;
        }
        if (!("subsystem" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subsystem"] = "";
        }
        if (!("event" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["event"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["operation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error_kind"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Session identity (v0.9.7): session_id identifies one
             * application launch; Seq is monotonic within the session and
             * EventID is unique per entry. Restarts are distinguishable by
             * session_id alone — no message parsing required.
             * v0.9.8.3: identity is emitted ONLY on correlated records.
             * @member
             * @type {string | undefined}
             */
            this["session_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["event_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Correlation (v0.9.7): parent_event_id links an event to the
             * event that caused it; batch_id groups a bulk test run;
             * test_id / config_id tie events to one test / one
             * configuration; core + pid + listener identify a core
             * process; duration_ms / status carry outcome data.
             * @member
             * @type {string | undefined}
             */
            this["parent_event_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["batch_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["test_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["config_id"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["core"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["pid"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["listener"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["duration_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["fields"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        const $$createField19_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField19_0($$parsedSource["fields"]);
        }
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}

/**
 * Level is a log severity.
 * @readonly
 * @enum {string}
 */
export const Level = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Severity levels in increasing order.
     */
    LevelDebug: "debug",
    LevelInfo: "info",
    LevelWarn: "warn",
    LevelError: "error",
};

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
