// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry is one structured runtime log record (§17).
 */
export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }
        if (!("ts" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ts"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("subsystem" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subsystem"] = "";
        }
        if (!("event" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["event"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("operation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation"] = "";
        }
        if (!("error_kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error_kind"] = "";
        }
        if (!("session_id" in $$source)) {
            /**
             * Session identity (v0.9.7): unique per application launch.
             * @member
             * @type {string}
             */
            this["session_id"] = "";
        }
        if (!("event_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["event_id"] = "";
        }
        if (!("parent_event_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parent_event_id"] = "";
        }
        if (!("batch_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["batch_id"] = "";
        }
        if (!("test_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["test_id"] = "";
        }
        if (!("config_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["config_id"] = "";
        }
        if (!("core" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["core"] = "";
        }
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("listener" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["listener"] = "";
        }
        if (!("duration_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duration_ms"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("fields" in $$source)) {
            /**
             * @member
             * @type {Object<string, any> | undefined}
             */
            this["fields"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}
