// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Entry is one structured runtime log record (§17).
 */
export class Entry {
    /**
     * Creates a new Entry instance.
     * @param {Partial<Entry>} [$$source = {}] - The source object to create the Entry.
     */
    constructor($$source = {}) {
        if (!("seq" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["seq"] = 0;
        }
        if (!("ts" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ts"] = "";
        }
        if (!("level" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["level"] = "";
        }
        if (!("subsystem" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subsystem"] = "";
        }
        if (!("event" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["event"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("operation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["operation"] = "";
        }
        if (!("error_kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error_kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Entry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry(/** @type {Partial<Entry>} */($$parsedSource));
    }
}
