// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * HealthReport separates process health from network health: a core
 * binary can be alive while its listener is broken, and only the
 * combination means the tunnel path is established.
 * 
 * Ladder (each step implies the previous ones were observed):
 * 
 * 	process alive → core started → local listener available →
 * 	protocol path established → connectivity verified
 * 
 * This report covers the first three steps; the connection manager
 * optionally verifies through-proxy connectivity on top.
 */
export class HealthReport {
    /**
     * Creates a new HealthReport instance.
     * @param {Partial<HealthReport>} [$$source = {}] - The source object to create the HealthReport.
     */
    constructor($$source = {}) {
        if (!("core" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["core"] = "";
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {InstanceState}
             */
            this["state"] = InstanceState.$zero;
        }
        if (!("process_alive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["process_alive"] = false;
        }
        if (!("listener_ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["listener_ready"] = false;
        }
        if (!("latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency_ms"] = 0;
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "0001-01-01T00:00:00.000Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HealthReport}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthReport(/** @type {Partial<HealthReport>} */($$parsedSource));
    }
}

/**
 * InstanceState is the explicit lifecycle state of one running core.
 * 
 * Transitions:
 * 
 * 	Created → Starting → Running → Stopping → Stopped
 * 	Starting → StartFailed | TimedOut
 * 	Running → Crashed | Unhealthy
 * @readonly
 * @enum {string}
 */
export const InstanceState = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * Instance lifecycle and error states. There are no ambiguous boolean
     * flags: the state machine is the single source of truth.
     */
    StateCreated: "created",
    StateStarting: "starting",
    StateRunning: "running",
    StateStopping: "stopping",
    StateStopped: "stopped",
    StateStartFailed: "start_failed",
    StateCrashed: "crashed",
    StateUnhealthy: "unhealthy",
    StateTimedOut: "timed_out",
};
