// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Protocol-core execution boundary models (engine/core).
 * @module
 */

/**
 * HealthReport separates process health from network health.
 */
export class HealthReport {
    /**
     * Creates a new HealthReport instance.
     * @param {Partial<HealthReport>} [$$source = {}] - The source object to create the HealthReport.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["core"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["state"] = undefined;
        }
        if (!("process_alive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["process_alive"] = false;
        }
        if (!("listener_ready" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["listener_ready"] = false;
        }
        if (!("latency_ms" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["latency_ms"] = 0;
        }
        if (!("checked_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["checked_at"] = "1970-01-01T00:00:00Z";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HealthReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HealthReport}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HealthReport(/** @type {Partial<HealthReport>} */($$parsedSource));
    }
}
