// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Mode is the user-facing tunnel mode.
 * @readonly
 * @enum {string}
 */
export const Mode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ModeDirect: no tunnel. All traffic leaves the system as-is.
     */
    ModeDirect: "direct",

    /**
     * ModeSystemProxy: Windows system proxy is set to the local
     * SOCKS/HTTP endpoint exposed by the active core. Browsers and
     * most user apps honour the system proxy. No kernel-level
     * routing.
     */
    ModeSystemProxy: "system_proxy",

    /**
     * ModeTUN: DISABLED (v0.9.8.6). TUN remains in the mode enum so
     * the UI can report it as unavailable/experimental, but Enable
     * always returns ErrTunExperimental until a safe, transactional
     * implementation exists. See tun_unavailable.go.
     */
    ModeTUN: "tun",
};

/**
 * State is the current tunnel state surfaced to the UI.
 */
export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {Mode}
             */
            this["mode"] = Mode.$zero;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["backend"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["bypass_list"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * redacted (no credentials)
             * @member
             * @type {string | undefined}
             */
            this["saved_proxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["saved_proxy_enable"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requires_elevation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["started_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bypass_list" in $$parsedSource) {
            $$parsedSource["bypass_list"] = $$createField4_0($$parsedSource["bypass_list"]);
        }
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
