// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Mode is the user-facing tunnel mode.
 * @readonly
 * @enum {string}
 */
export const Mode = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * ModeDirect: no tunnel. All traffic leaves the system as-is.
     */
    ModeDirect: "direct",

    /**
     * ModeSystemProxy: Windows system proxy is set to the local
     * SOCKS/HTTP endpoint exposed by the active core. Browsers and
     * most user apps honour the system proxy. No kernel-level
     * routing.
     */
    ModeSystemProxy: "system_proxy",

    /**
     * ModeTUN: REAL Windows tunnel mode (v0.11.3) backed by the
     * managed sing-box core's native TUN inbound (Wintun). The
     * activation path is transactional and observed — see
     * tun.go. TUN is NOT a kill switch and must never be
     * described as one: routing is not packet filtering.
     */
    ModeTUN: "tun",
};

/**
 * OwnershipStatus is the redacted ownership view for the UI: whether
 * a marker exists, its phase, endpoint, age and the recorded previous
 * state — the "FreeIran proxy ownership / saved previous state /
 * recovery status" surface (v0.10.2 § Windows system-proxy UX).
 */
export class OwnershipStatus {
    /**
     * Creates a new OwnershipStatus instance.
     * @param {Partial<OwnershipStatus>} [$$source = {}] - The source object to create the OwnershipStatus.
     */
    constructor($$source = {}) {
        if (!("present" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["present"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["phase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["schema_version"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["enabled_at_ms"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {SystemProxySnapshot | undefined}
             */
            this["previous"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OwnershipStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OwnershipStatus}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("previous" in $$parsedSource) {
            $$parsedSource["previous"] = $$createField5_0($$parsedSource["previous"]);
        }
        return new OwnershipStatus(/** @type {Partial<OwnershipStatus>} */($$parsedSource));
    }
}

/**
 * State is the current tunnel state surfaced to the UI.
 */
export class State {
    /**
     * Creates a new State instance.
     * @param {Partial<State>} [$$source = {}] - The source object to create the State.
     */
    constructor($$source = {}) {
        if (!("mode" in $$source)) {
            /**
             * @member
             * @type {Mode}
             */
            this["mode"] = Mode.$zero;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["backend"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["bypass_list"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * redacted (no credentials)
             * @member
             * @type {string | undefined}
             */
            this["saved_proxy"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["saved_proxy_enable"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["requires_elevation"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["started_at"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * TUN carries the live TUN snapshot while the TUN mode is in
             * use (or the last TUN outcome). Nil for system-proxy/direct
             * states.
             * @member
             * @type {TUNSnapshot | null | undefined}
             */
            this["tun"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new State instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {State}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        const $$createField10_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bypass_list" in $$parsedSource) {
            $$parsedSource["bypass_list"] = $$createField4_0($$parsedSource["bypass_list"]);
        }
        if ("tun" in $$parsedSource) {
            $$parsedSource["tun"] = $$createField10_0($$parsedSource["tun"]);
        }
        return new State(/** @type {Partial<State>} */($$parsedSource));
    }
}

/**
 * SystemProxySnapshot is a redacted view of the system proxy state.
 */
export class SystemProxySnapshot {
    /**
     * Creates a new SystemProxySnapshot instance.
     * @param {Partial<SystemProxySnapshot>} [$$source = {}] - The source object to create the SystemProxySnapshot.
     */
    constructor($$source = {}) {
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["server"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["bypass"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * raw override string from WinINet
             * @member
             * @type {string | undefined}
             */
            this["override"] = undefined;
        }
        if (!("saved" in $$source)) {
            /**
             * previous settings saved?
             * @member
             * @type {boolean}
             */
            this["saved"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.10.2 fidelity fields. The v0.10.1 marker (recovery record)
             * did not persist these, so legacy markers parse with zero
             * values and recovery derives the mode from Enabled/Server —
             * documented as the v1 fidelity limit.
             * 
             *   AutoConfigURL — the PAC/autoconfig URL (INTERNET_PER_CONN_AUTOCONFIG_URL)
             *   AutoDetect    — the PROXY_TYPE_AUTO_DETECT flag bit
             *   Flags         — the raw INTERNET_PER_CONN_FLAGS value (diagnostics)
             * @member
             * @type {string | undefined}
             */
            this["autoconfig_url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["autodetect"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["flags"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * v0.10.3 fidelity field: the connection's autodiscovery
             * settings (INTERNET_PER_CONN_AUTODISCOVERY_FLAGS, option 5 —
             * the AUTO_PROXY_FLAG_* mask that Windows keeps BESIDE the
             * PROXY_TYPE_AUTO_DETECT flag bit). v0.10.2 never captured or
             * restored it, so a session could not faithfully restore the
             * WPAD autodetection state it had saved: the AUTO_PROXY flags
             * live in this option, not in INTERNET_PER_CONN_FLAGS, and
             * Windows re-derives the AUTO_DETECT flag bit from it on query.
             * Zero = not captured (legacy v1 records) — the comparison
             * algebra treats zero as "unknown", never as "absent".
             * @member
             * @type {number | undefined}
             */
            this["autodiscovery_flags"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemProxySnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemProxySnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bypass" in $$parsedSource) {
            $$parsedSource["bypass"] = $$createField2_0($$parsedSource["bypass"]);
        }
        return new SystemProxySnapshot(/** @type {Partial<SystemProxySnapshot>} */($$parsedSource));
    }
}

/**
 * TUNSnapshot is a redacted view of the TUN state. v0.11.3 extends
 * the v0.9.8.5 model with the fields the UI needs to tell the truth:
 * which core runs the dataplane, the lifecycle status, what was
 * observed, and the deployment design.
 */
export class TUNSnapshot {
    /**
     * Creates a new TUNSnapshot instance.
     * @param {Partial<TUNSnapshot>} [$$source = {}] - The source object to create the TUNSnapshot.
     */
    constructor($$source = {}) {
        if (!("available" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["available"] = false;
        }
        if (!("installed" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["installed"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["interface_name"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ipv4_address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ipv6_address"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["dns_servers"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["routes"] = undefined;
        }
        if (!("requires_elevation" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["requires_elevation"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Backend names the TUN dataplane ("sing-box native TUN
             * (Wintun)").
             * @member
             * @type {string | undefined}
             */
            this["backend"] = undefined;
        }
        if (!("active" in $$source)) {
            /**
             * Active reports an OBSERVED, VERIFIED session (interface +
             * tunneled request), never merely a started process.
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * Status is the lifecycle state surfaced to the UI:
             * off | starting | active | stopping | failed.
             * @member
             * @type {string | undefined}
             */
            this["status"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Core is the sing-box version running the dataplane.
             * @member
             * @type {string | undefined}
             */
            this["core"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Configuration is the redacted display form of the
             * configuration routed through the TUN.
             * @member
             * @type {string | undefined}
             */
            this["configuration"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Details carries the last failure (status=failed) or the
             * stale-state note.
             * @member
             * @type {string | undefined}
             */
            this["details"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TUNSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TUNSnapshot}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType1;
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns_servers" in $$parsedSource) {
            $$parsedSource["dns_servers"] = $$createField5_0($$parsedSource["dns_servers"]);
        }
        if ("routes" in $$parsedSource) {
            $$parsedSource["routes"] = $$createField6_0($$parsedSource["routes"]);
        }
        return new TUNSnapshot(/** @type {Partial<TUNSnapshot>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SystemProxySnapshot.createFrom;
const $$createType1 = $Create.Array($Create.Any);
const $$createType2 = TUNSnapshot.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
